### ISSUE TITLE
Reported hashrate oscillating (0.15.0dev2)

### ISSUE THREAD

**Issue by igy137** [ethereum-mining/ethminer#1016]
Hi 

With 0.15.0dev2 I get something like the attached graph. What I find interesting in it, the reported hash ripples/oscillates +-10Mh, pretty much regularly with a period of 40 minutes or so.

![miner](https://user-images.githubusercontent.com/37290114/39067054-a1725cf2-44d7-11e8-8e93-155add59fefe.jpg)

With 0.14.0dev3 I've never seen this it's always a flat line.

igy

**Comment by AndreaLanfranchi** [comment]
Please test lates 0.15 dev and report.
Some work has been done about this matter.

**Comment by germanlarrosa** [comment]
Hi, 

I am also dealing with hashrate oscilation reported in the ethermine console. I have 13 rx 580, expected to have around 25-28mh/s in every gpu but actually I am getting different hashrates in every gpu fluctuating bewteen 2-3 mh/s to 28mh/s randomically in almost every card. Is that normal ? Some miners reported to me stable hashrates around 28mh/s on their rigs. 
Also Ive read that one possible solution would be switching to some other pool (currently using nanopool) in order to get a more stable hashrate.
Also tried with different version of ethminer (currently using 0.14) but got the same result.

Note: I also have two p106-100 nvidia cards, when running ethermine on those I did get a stable hashrate of 20-21mh/s for a long test period.

Thanks!
German.
