### ISSUE TITLE
Computer reset everytime ethminer starts...

### ISSUE THREAD

**Issue by mauadib** [ethereum-mining/ethminer#103]
Hi guys,

I've got XUbuntu 16.04 desktop working with a 6 x GTX 1070 with all the over clocking bells and whistles working and power limitation and I'd really like to try your ethminer code. I have the latest NVidia driver (381) installed and I can run Claymore with no issues, but every time I start the ethminer the computer just resets. Is there something I need to do in config to sort this issue out?

Update, I've also tried this on a windows 10 pro build with NVidia drivers 382 on an Asus GeForce GTX 1070 OC GAMING 8GB x 6 cards rig. Consistently get random PC resets with no overclocking on stock frequencies. These cards have an unmodified BIOS, looks like a driver crash, I have tried the 384 drivers which also manifest the same problem, but this causes issues with Claymore. Claymore on the 382 drivers runs for days without problems on windows 10 pro. Any thoughts would be appreciated.

Kind regards.

**Comment by JHGitty** [comment]
Currently the newest nvidia driver is version 384.76 (available since 2017.6.29): http://www.nvidia.de/download/driverResults.aspx/120603/de

I think your crashes are somehow hardware-related. Please try to reproduce it on any benchmark software to be sure that your system itself is stable enough to run a miner.

Please also try the new miner version 0.11.0 which was released 1 day ago.
