### ISSUE TITLE
Fucking project

### ISSUE THREAD

**Issue by alptolga** [ethereum-mining/ethminer#1040]
I just want to know like the other people. What is going on about ethminer. There are 2 releases which are named 0.14 (more then 10 published) 0.15 (5 released) nobody knows anything about ethminer (since 0.13 published) so what the fucked you do

**Comment by AndreaLanfranchi** [comment]
I think this rant does not deserve any further comment aside the fact you're free to use any other miner eventually paying for it.
Bye

**Comment by alptolga** [comment]
So you can write this opinion to the main page. People spend their energy and equipment. You don't have right to say ''this is free if you don't like it don't use it'' Before you say this, you must put some rules. İPeople aren't lab. animal for using your own ego.

**Comment by alptolga** [comment]
@smurfy 
You missed the point. After you released 0.13, I don't see any information about 0.14 and 0.15. Nobody knows why you release 2 different version. What are their differences.... 
 I know there are many other miners out there. Many of them have 1 % fee. This is not too much and paying fee is not our point too. We just need explanation.

**Comment by smurfy** [comment]
Well, then visit us in the gitter chat and ask, instead of ranting. Ranting does not help anyone.
For the difference, i'm a bit out of the loop, because i am busy with other stuff, but 0.14 will be the next release, 0.15 the one after that. 

Since we changed a lot, which made ethminer a bit unstable, we try to make 0.14 stable and add only bugfixes and no new features (0.14 has new features compared to 0.13, but is now feature freeze), while 0.15 is on par with master and gets the fixes+possible new features.

**Comment by AndreaLanfranchi** [comment]
@alptolga 

> People spend their energy and equipment. You don't have right to say ''this is free if you don't like it don't use it''

Do you think the code of a miner self-generates automagically or do you reckon we do spend our energy on a voluntary basis and give you the results (whichever they are) for free ?
You as a miner invest in your equipment and expect a revenue ... we as FOSS devs invest our time and DO NOT expect a return. 

> After you released 0.13, I don't see any information about 0.14 and 0.15. Nobody knows why you release 2 different version. What are their differences....

As in all FOSS experience you have to invest some additional time in reading, understanding and asking. Github keeps track of every addition and/or deletion issued on the code: they're all public to see.
But if you expect a project like this to offer you some sort of SLA ... well you're in the wrong place.

**Comment by Hakkk2002** [comment]
- 0.13: "stable version".
- 0.14 **rc**: "release candidate", which means new features added on top of 0.13 are mostly fixed but there may be still bugs and more testing is needed. Once everything is (likely) done the "rc" tag will be removed and it becomes the stable 0.14 version.
- 0.15 **dev**: latest build in development, quite unstable. New features on top of 0.14 are gradually added in.

This is how software development works. You cannot wait until all bugs fixed before you start adding new features. You cannot add new features directly to a release candidate because that will introduce new bugs so that the release candidate will never become a stable version.

**Comment by alptolga** [comment]
@Hakkk2002 
I think you need to read my messages again. Most of us need need to know what we use
For example: 0.14 rc1 opencl improvements   ( so there is no need to update if you use cuda )
0.14 rc2 cuda improvements ( so you can keep your opencl supported rigs )
So that you can keep your rigs with a stable release that you need untill they releasea stable one. I think it is clear.

**Comment by Hakkk2002** [comment]
@alptolga So you mean something like a change log in the release page? That exists only for stable releases, the last one being 0.13.0. Maintaining change logs for pre-releases takes extra work for projects with fast iterations and apparently developers here opt not to do that. Still, all changes of pre-releases can be digged out from records of commits, although this is not straightforward for ordinary people who do not use Git.

**Comment by uvtzxpm** [comment]
@alptolga Imagine if you spent hours and hours of your time to create/maintain an open source (and free!) miner, and then some guy comes along and posts "Fucking project", whining about there being no changelogs.

I mean, come on... remember that there are real people on the other side of the screen.

Someone else has now asked for changelogs politely, like a normal human being:

https://github.com/ethereum-mining/ethminer/issues/1088

So, hopefully there will be changelogs to come in the future.
