### ISSUE TITLE
Option -X will use Nvidia GPU twice

### ISSUE THREAD

**Issue by chfast** [ethereum-mining/ethminer#1049]

**Comment by smurfy** [comment]
I would prefer to refactor the way -U, -G and -X works.
I really like the way claymore does the selection, its basically -X by default.

I would keep an option to force opencl on nvidia, but otherwise if cuda and cards are detected run cuda for the cards and opencl for others if detected.

I would also like an option to run opencl on nvidia and amd at the same time. (aka multiple ocl platforms), its less of nvidia+amd and more that in the past its hard for the users to understand that they need to select a platform. so i would combine all platforms devices to just opencl devices.

**Comment by chfast** [comment]
I agree.

**Comment by AndreaLanfranchi** [comment]
Resolved by #1704 

@smurfy the behavior is exactly what you described. -X is on by default and you can have multiple oclPltaforms. NVIDIA detection takes precedence.
