### ISSUE TITLE
Not exiting on no work given

### ISSUE THREAD

**Issue by Yorper** [ethereum-mining/ethminer#1111]
As per this bug #672 

Using 0.14.0RC10 it still does not exit on no work given. Unless I'm completely missing something, this is the command issued...

./ethminer --exit -U -P user.name:password@server.address.com:port

The miner just sits in a never ending loop of "No work. Pause for 3 s". If i'm missing something then sorry for the confusion, if someone could set me straight I'd be grateful. Until then I'm back to using 0.11.

Thanks.

**Comment by editorfatih** [comment]
I have encountered the same problem and downgrade to 0.14.0.dev3 tag
The only difference is I'm using both AMD and Nvidia cards, opencl platform correct

`/ethminer -X --opencl-platform 0 --farm-recheck 200 -P $POOL_URL`

**Comment by smurfy** [comment]
You guys are describing different behavoirs

1. #672 describes if pool connections drops and it cant reconnect. It exits miner. Commandline would be:  ``-P exit`` AFTER the normal pool connection
2. ``--exit`` is if a CUDA or OPENCL error occures miner will exit.
3. If you get ``"No work. Pause for 3 s"`` you can adjust ``--work-timeout`` so it will disconnect after a while. It should work in combination with 1. To fallback to exit after x times no work timout occures.

**Comment by editorfatih** [comment]
>  ethminer -X --opencl-platform 0 --farm-recheck 200 -P stratum1+tcp://wallethash@eth-eu1.nanopool.org:9999/pool01/dummymail@dumyy.dmy --exit --work-timeout 200
  m  22:50:45|ethminer|  ethminer version 0.14.0rc10
  m  22:50:45|ethminer|  Build: linux / release +git. af0eecb
  ℹ  22:50:45|ethminer|  Found suitable OpenCL device [ Ellesmere ] with 4281323520  bytes of GPU memory
 cu  22:50:45|ethminer|  Using grid size 8192 , block size 128
  ℹ  22:50:45|ethminer|  Selected pool eth-eu1.nanopool.org:9999
  m  22:50:45|ethminer|  not-connected
  ℹ  22:50:45|stratum |  Trying 164.132.108.171:9999 ...
  ℹ  22:50:47|stratum |  Connected to eth-eu1.nanopool.org  [164.132.108.171:9999]
  ℹ  22:50:47|stratum |  Spinning up miners...
  ℹ  22:50:47|cuda-0  |  No work. Pause for 3 s.
 cl  22:50:47|cl-1    |  No work. Pause for 3 s.
 cl  22:50:47|cl-2    |  No work. Pause for 3 s.
 cl  22:50:47|cl-3    |  No work. Pause for 3 s.
 cl  22:50:47|cl-4    |  No work. Pause for 3 s.
  ℹ  22:50:47|stratum |  Logged in to eth-proxy server
  ℹ  22:50:47|stratum |  New pool difficulty:  10.00 gigahashes
  ℹ  22:50:47|stratum |  New job #c1928ba2…   eth-eu1.nanopool.org [164.132.108.171:9999]
  ℹ  22:50:50|cuda-0  |  Initialising miner 0
 cl  22:50:50|cl-1    |  New seed #e6073b55…
 cl  22:50:50|cl-2    |  New seed #e6073b55…
 cl  22:50:50|cl-3    |  New seed #e6073b55…
 cl  22:50:50|cl-4    |  New seed #e6073b55…

Hi, as you said, I tried --work-timeout. I re-run several times, few times did work but sometimes get same result again.

**Comment by Yorper** [comment]
Ok i'm clearly missing something then. This is the command i now issue.

./ethminer --farm-retries 0 -U -P stratum+tcp://user.name:password@us-east.ethash-hub.miningpoolhub.com:12020 --exit --work-timeout 1

It just runs an endless loop of trying to reconnect, waiting for no work then reconnecting.... All i'm trying to make it do is connect, if connection is refused EXIT the application and if there is no work EXIT the application... If i move the exit word removing the -- to after the -P it just gives an error.

This worked perfectly fine on 0.11 using the following...

./ethminer --farm-retries 0 -G -S us-east.ethash-hub.miningpoolhub.com:12020 -O user.name:password -FS exit

So sorry for my apparent confusion, but how on earth do i make this work like it used to?

**Comment by AndreaLanfranchi** [comment]
Solved per #1114

**Comment by smurfy** [comment]
@Yorper please use ``-P stratum+tcp://exit:1`` AFTER the main pool connection, the miner will exit after some retries without receiving work from pool this way.

**Comment by Yorper** [comment]
Thank you @smurfy for clarifying what had to be done..... So far everything seems to be working OK now. Thank you once again!
:+1:

**Comment by editorfatih** [comment]
Thank you @smurfy, but i have still same problem, am i doing wrong?

`ethminer -X --opencl-platform 0 --farm-recheck 200 -P stratum1+tcp://wallethash@eth-eu1.nanopool.org:9999/pool01/dummymail@dumyy.dmy -P stratum+tcp://exit:1  --exit --work-timeout 20`


>   m  13:15:12|ethminer|  ethminer 0.15.0.dev10-18+commit.86558a2d
  m  13:15:12|ethminer|  Build: linux / release
  ℹ  13:15:12|ethminer|  Found suitable OpenCL device [ Ellesmere ] with 4281323520  bytes of GPU memory
  ℹ  13:15:12|ethminer|  Found suitable OpenCL device [ Ellesmere ] with 8576290816  bytes of GPU memory
  ℹ  13:15:12|ethminer|  Found suitable OpenCL device [ Ellesmere ] with 4281323520  bytes of GPU memory
  ℹ  13:15:12|ethminer|  Found suitable OpenCL device [ Ellesmere ] with 4281323520  bytes of GPU memory
 cu  13:15:12|ethminer|  Using grid size 8192 , block size 128
  ℹ  13:15:12|ethminer|  Selected pool eth-eu1.nanopool.org:9999
  m  13:15:12|ethminer|  not-connected
  ℹ  13:15:12|stratum |  Trying 213.32.74.230:9999 ...
  ℹ  13:15:12|stratum |  Connected to eth-eu1.nanopool.org  [213.32.74.230:9999]
  ℹ  13:15:12|stratum |  Spinning up miners...
  ℹ  13:15:12|cuda-0  |  No work. Pause for 3 s.
 cl  13:15:12|cl-1    |  No work. Pause for 3 s.
 cl  13:15:12|cl-2    |  No work. Pause for 3 s.
 cl  13:15:12|cl-3    |  No work. Pause for 3 s.
 cl  13:15:12|cl-4    |  No work. Pause for 3 s.
  ℹ  13:15:15|cuda-0  |  No work. Pause for 3 s.
 cl  13:15:15|cl-1    |  No work. Pause for 3 s.
 cl  13:15:15|cl-2    |  No work. Pause for 3 s.
 cl  13:15:15|cl-3    |  No work. Pause for 3 s.
 cl  13:15:15|cl-4    |  No work. Pause for 3 s.
  ℹ  13:15:18|cuda-0  |  No work. Pause for 3 s.
 cl  13:15:18|cl-1    |  No work. Pause for 3 s.

**Comment by Yorper** [comment]
Remove the "--exit" @editorfatih and your should be fine.

**Comment by melt7777** [comment]
Pardon me and I hope that I have not misunderstood.... But.... Having to specify that you want the application to exit properly, as a pool, in this way stratum+tcp://exit:1,  is a crude band-aid at best. Please fix the code to behave properly without this userspace hack.

**Comment by editorfatih** [comment]
Sorry guys but sometimes does not work for me, i did try all combination, it hangs like that

`/usr/local/bin/ethminer -X --opencl-platform 0 --farm-recheck 200 -P stratum1+tcp://wallethash@eth-eu1.nanopool.org:9999/pool01/dummymail@dumyy.dmy -P stratum+tcp://exit:1 -RH --work-timeout 200
`

>   m  13:41:01|ethminer|  ethminer 0.15.0.dev10-18+commit.86558a2d
  m  13:41:01|ethminer|  Build: linux / release
  ℹ  13:41:01|ethminer|  Found suitable OpenCL device [ Ellesmere ] with 4281323520  bytes of GPU memory
  ℹ  13:41:01|ethminer|  Found suitable OpenCL device [ Ellesmere ] with 8576290816  bytes of GPU memory
  ℹ  13:41:01|ethminer|  Found suitable OpenCL device [ Ellesmere ] with 4281323520  bytes of GPU memory
  ℹ  13:41:01|ethminer|  Found suitable OpenCL device [ Ellesmere ] with 4281323520  bytes of GPU memory
 cu  13:41:01|ethminer|  Using grid size 8192 , block size 128
  ℹ  13:41:01|ethminer|  Starting web server on port 8888
  ℹ  13:41:01|ethminer|  Selected pool eth-eu1.nanopool.org:9999
  m  13:41:01|ethminer|  not-connected
  ℹ  13:41:01|stratum |  Trying 79.137.82.70:9999 ...
  ℹ  13:41:01|stratum |  Connected to eth-eu1.nanopool.org  [79.137.82.70:9999]
  ℹ  13:41:01|stratum |  Spinning up miners...
  ℹ  13:41:01|cuda-0  |  No work. Pause for 3 s.
 cl  13:41:01|cl-1    |  No work. Pause for 3 s.
 cl  13:41:01|cl-2    |  No work. Pause for 3 s.
 cl  13:41:01|cl-3    |  No work. Pause for 3 s.
 cl  13:41:01|cl-4    |  No work. Pause for 3 s.
  ℹ  13:41:04|cuda-0  |  No work. Pause for 3 s.
 cl  13:41:04|cl-1    |  No work. Pause for 3 s.
 cl  13:41:04|cl-2    |  No work. Pause for 3 s.
 cl  13:41:04|cl-3    |  No work. Pause for 3 s.
 cl  13:41:04|cl-4    |  No work. Pause for 3 s.
  ℹ  13:41:07|cuda-0  |  No work. Pause for 3 s.
 cl  13:41:07|cl-2    |  No work. Pause for 3 s.
 cl  13:41:07|cl-3    |  No work. Pause for 3 s.
 cl  13:41:07|cl-1    |  No work. Pause for 3 s.
 cl  13:41:07|cl-4    |  No work. Pause for 3 s.
  ℹ  13:41:10|cuda-0  |  No work. Pause for 3 s.
 cl  13:41:10|cl-2    |  No work. Pause for 3 s.
 cl  13:41:10|cl-3    |  No work. Pause for 3 s.
 cl  13:41:10|cl-4    |  No work. Pause for 3 s.
 cl  13:41:10|cl-1    |  No work. Pause for 3 s.
 cl  13:41:13|cl-2    |  No work. Pause for 3 s.
 cl  13:41:13|cl-1    |  No work. Pause for 3 s.
 cl  13:41:13|cl-3    |  No work. Pause for 3 s.
  ℹ  13:41:13|cuda-0  |  No work. Pause for 3 s.
 cl  13:41:13|cl-4    |  No work. Pause for 3 s.
 cl  13:41:16|cl-1    |  No work. Pause for 3 s.
 cl  13:41:16|cl-2    |  No work. Pause for 3 s.
 cl  13:41:16|cl-3    |  No work. Pause for 3 s.
  ℹ  13:41:16|cuda-0  |  No work. Pause for 3 s.
 cl  13:41:16|cl-4    |  No work. Pause for 3 s.
 cl  13:41:19|cl-3    |  No work. Pause for 3 s.
 cl  13:41:19|cl-4    |  No work. Pause for 3 s.
  ℹ  13:41:19|cuda-0  |  No work. Pause for 3 s.
 cl  13:41:19|cl-1    |  No work. Pause for 3 s.
 cl  13:41:19|cl-2    |  No work. Pause for 3 s.
...

I think this OpenCL + CUDA ( mixed AMD/Nvidia cards) problem, because there is no problem in -U or -G mode.
How can i debug this problem ?

**Comment by AndreaLanfranchi** [comment]
Actually you can't.
-X is broken.

Only option, atm, is you run two separate instances of ethminer: one for CUDA gpus and the other for OpenCL ones. Use-U with --cuda-devices for CUDA and -G with --opencl-devices for OpenCL respectively.

**Comment by editorfatih** [comment]
@AndreaLanfranchi 
why we do not prevent endless loop ? 
ex: If --exit argument exists and I get n times "No work. Pause for 3 s." then close miner. :/

**Comment by AndreaLanfranchi** [comment]
Believe me ... we're trying hard.
Ethminer is a project where many many hands have been working on and it's not easy to understand logic someone else has implemented with poor or no documentation at all.
