### ISSUE TITLE
CUDA error in func 'ethash_cuda_miner::search' at line 365 : unspecified launch failure. 

### ISSUE THREAD

**Issue by momo00o** [ethereum-mining/ethminer#115]
is there a way to make the software restart it self automatically after it stops because of an error 
((CUDA error in func 'ethash_cuda_miner::search' at line 365 : unspecified launch failure.))

i tried this mining software twice and it stopped mining after 50-70 minutes

**Comment by mauadib** [comment]
I've been seeing this error as well after about 10 minutes.

**Comment by thatspsychotic** [comment]
I get this error, sometimes coupled with a blank screen, when I've pushed my memory overclock a little too high.  I suspect that it occurs when mem overclock stability is marginal.

**Comment by soxnaples87** [comment]
It's possible to create an handler that can restart the script?

**Comment by soxnaples87** [comment]
It's possible to create an handler that can restart the script?

**Comment by z1ck** [comment]
GTX970 contains 3.5 Gb of fast memory (192 Gb/s) and 512 Mb slow memory (28 Gb/s). We need to use only fast memory I think.

**Comment by momo00o** [comment]
+1

**Comment by Golempl** [comment]
I have same problem, my rig is overclocked but been rock solid stable (7x 1060 6g , 1x 1060 3g), performance improved from 183mh to 200mh. My setup been working stable for weeks with claymore, however using ethminner crashing every 1-6 hours. 
Some info which may be useful for debug:
Pentium G4400 (fix for slow typing at start is working)
Mobo:  ASUS PRIME Z270-P Z270 
Windows 10 , NVML version: 8.382.53,
OC: 65%tdp/temp 66c max , -400 gpu, +850mem, 100% fan

Power usage: 790W running claymore, 810W running eth minner, still thinking if additional power draw cause additional heat and this cause crashes, howerver thats only 2.5W more per card which is +2MH/s per card

There is no problem with power supply and theres more power available.

I checked my claymore logs for any problems/watchdog info, but there were no crash info, just only 1 card having problem with fan speed reading,  doesn't affect ethminner/claymore.

Ethminner version is lastest 0.11 , after it crash and I try to close CMD window sometimes PC reboots.
Please add any watchdog, like if MH/s drop to 0 for more than xx sec  do restart - at least for Windows , because theres no tools like linux have to process output.

**Comment by jimmykl** [comment]
Different miners stress cards in different ways. My rigs crashed a lot when I moved from Claymore and tried using the same overclocks.

I would suggest bumping up the power level, increase core and reduce memory overclocks until it becomes more stable. It will take a while to find the balance but you'll still be hashing faster than Claymore (and no fees as well).

I setup Windows to automatically start the miner and scheduled a reboot every x hours. Ok you lose a few minutes of mining but it seems to help with the errors which occur after running for a long stretch.

If you absolutely need a watchdog then you might need to use another miner until it's implemented.

**Comment by dhjw** [comment]
I made a PHP script to kill ethminer if it stops hashing:
```
#!/usr/bin/php
<?php
$start=time();
putenv("PATH=/bin:/usr/bin:/usr/local/bin");
while($line=fgets(STDIN)){
	if(time()-$start<=30){ echo "[*] $line\n"; continue; } // ignore first 30s
	if(strpos($line," 0.00MH/s")!==false){
		echo "got error. line= $line\n";
		echo "killing ethminer\n";
		$date=trim(shell_exec('date'));
		passthru("echo \"$date ethminer crash detected. killing\" >> ~/ethminer.log");
		passthru("killall -9 ethminer");
	} else echo "$line\n";
}
```
run ethminer in a loop and pipe it like this:
`while [ 1 ]; do ethminer ... 2>&1 | mine-monitor; done`

**Comment by jimmykl** [comment]
@momo00o The underlying error in ethash_cuda_miner::search has been reported several times. 

To make things easier for the devs could you please close this issue and add your info to the discussion at https://github.com/ethereum-mining/ethminer/issues/72 Thanks!
