### ISSUE TITLE
Specify OpenCL dir/lib when compiling from source

### ISSUE THREAD

**Issue by Bliss3d** [ethereum-mining/ethminer#1324]
So I really would like to specify my OpenCL dir/lib when compiling from source.
so I used: 

cmake .. -DCUDA_ENABLE=OFF -DOpenCL_INCLUDE_DIR=/opt/rocm/opencl/include/ -DOpenCL_LIBRARY=/opt/rocm/opencl/lib/x86_64/libOpenCL.so

However I get this warning:

CMake Warning:
  Manually-specified variables were not used by the project:

    CUDA_ENABLE
    OpenCL_INCLUDE_DIR
    OpenCL_LIBRARY

So, the opencl dir/lib I specified were not used to compile - and as a result the miner does not work.

**Comment by StefanOberhumer** [comment]
Not sure if this fits your requirements but try https://github.com/StefanOberhumer/ethminer/tree/CL-Own-CL-Library.

**Comment by saleelk** [comment]
I had a question about how ethminer loads the OpenCL apis, without the ICD being explicitly present on the system.

**Comment by saleelk** [comment]
Nevermind, found it. I guess it links the ICD statically
https://docs.hunter.sh/en/latest/packages/pkg/OpenCL.html?highlight=OpenCL 

And that picks old ICD, since my pull request isnt merged with master yet

**Comment by mrheat** [comment]
Dont know if this belongs here, but it seems thats part of our problem with nallatech BSP, the manual says: 

6.5.2.2 Switching to the Client Driver (FCD/ICD)
Nallatech have supplied the 17.x version of this BSP package installer to not setup the FCD as part of
the installation. If you need to use the client driver approach (FCD/ICD):
1. Copy the FCD file (board/nalla_pcie/nalla_pcie.fcd) to /opt/Intel/OpenCL/Boards/nalla_pcie.fcd.
This file is required for the new OpenCL client driver approach.
2. Copy the Altera ICD file from ${INTELFPGAOCLSDKROOT}/Altera.icd to /etc/OpenCL/vendors/Altera.icd. This file is also required for the new OpenCL client driver approach.
3. The installer has also included alternative board_env xml files for the ICD/FCD and non ICD/FCD
use cases. There are two files installed into the board package root (nalla_pcie): board_env.icd
(xml using the ICD/FCD approach) and board_env.old (xml using the non ICD/FCD approach)
4. Copy the board_env.icd over the board_env.xml to use the required ICD/FCD library approach.

Guess i ask nallatech first about some clarification what is what and needed when and so on.

**Comment by jean-m-cyr** [comment]
Closing... not ethminer issue.

**Comment by akostadinov** [comment]
FYI, for anybody trying to build ethminer for ROCm, you can do the following (thanks to @StefanOberhumer's suggestion):

- edit `ethminer/libethash-cl/CMakeLists.txt`
- comment out `hunter_add_package(OpenCL)` and `find_package(OpenCL CONFIG REQUIRED)`
- add the following in place of the above two
```
        set(OpenCL_INCLUDE_DIR "/opt/rocm/opencl/include/")
        set(OpenCL_LIBRARIES "/opt/rocm/opencl/lib/x86_64/libOpenCL.so")
        add_library(rocmcl INTERFACE)
        target_include_directories(rocmcl INTERFACE ${OpenCL_INCLUDE_DIR})
        target_link_libraries(rocmcl INTERFACE ${OpenCL_LIBRARIES})
```
- change line `target_link_libraries(ethash-cl PRIVATE OpenCL::OpenCL)` to `target_link_libraries(ethash-cl PRIVATE rocmcl)`

Then things should compile properly. But honestly I didn't see any positive difference compared to whatever `hunter` did. On the other hand will be very useful if `ethminer` provided an easy way to select some particular OpenCL library instead of heavily modifying `CMakeLists.txt`.
