### ISSUE TITLE
Nonce 0xf3fc94bf177b1d49^[[0m wasted. Waiting for connection ...corrupted size vs. prev_size

### ISSUE THREAD

**Issue by zorohakobyan** [ethereum-mining/ethminer#1357]
![2018-07-15 18-59-30](https://user-images.githubusercontent.com/36232590/42735227-72d46af2-8861-11e8-8dc8-ba1fabe579b3.png)

Hello!
   I see this kind of error first time. (before i had something like "connection error, trying to connect...)
Can someone tell me please what kind of error is it and maybe there is some solutions for this? 
Thanks in advance!

**Comment by AndreaLanfranchi** [comment]
If the pool does not respond to a share submission within 2 seconds then ethminer disconnects and tries to reconnect. The value of 2 seconds is the default of argument --response-timeout
It may happen that during disconnection/reconnection another share is found but this is "wasted" because there is no connection yet.
This explains the first part.

The second part "corrupted size vs prev_size" is an error in memory allocation. 
Would be difficoult to reproduce as rigs with 13 gpus are quite rare.

**Comment by zorohakobyan** [comment]
Thank you very much!
 But  in fact this rig is working well more than 3 months, just with 12 GPUs   ;)
the last one is added some days ago.

**Comment by zorohakobyan** [comment]
Some ideas to restart miner when this is happening? 
The miner just stopped  (not freeze, like pid is killed) my watchdog script is not helping too (it's not restarted the miner).

**Comment by AndreaLanfranchi** [comment]
If you're on Linux I would suggest this very simple but effective technique

```
until ./ethminer --exit [your other args here]; do
    echo "Miner stopped with exit code $?.  Respawning.." >&2
    sleep 10
done

```

This will cause ethminer to restart on every error

**Comment by zorohakobyan** [comment]
BIG THANKS!
