### ISSUE TITLE
setting for DAG data generation size

### ISSUE THREAD

**Issue by deepline1986** [ethereum-mining/ethminer#1360]
Hi,

Can I set the DAG data generation size for ethminer? The 1GB DAG data generation always takes me 10 minutes because my system performance is low.

My personal development server equiped an intel J1900 CPU which  has the limited performance.
I set up a private chain on the server which defined a very low difficulty. That means the DAG data is not useful for me.
I want to use the integrated graphics for the mining and then the CPU will be free for other usage.
The opencl driver is beignet 1.3 which works on the ethminer.
But it will take almost 10 minutes to complete the 1GB DAG data computing.
Is it possible to add the args for the DAG data generation size?
Or where is the code to define the DAG data generation size that I can change?
Thanks a lot.

**Comment by AndreaLanfranchi** [comment]
Ethminer does not set DAG size. 
DAG size it's dictated by epoch of the blockchain. You can not set an arbitrary DAG size.

**Comment by AndreaLanfranchi** [comment]
> That means the DAG data is not useful for me.

Do not know which are your mining intentions however if you want to mine ETHASH algorythm be advised that DAG is the culprit. So the statement above does not make any sense.

**Comment by AndreaLanfranchi** [comment]
I'll try explain the steps ethminer takes

1. It connects to a pool
2. It receives the first job
3. On behalf of the first job ethminer computes the epoch and consequentially computes DAG size.
4. If resulting DAG size can fit into GPU memory the GPU (or the GPUs) are instructed to build the DAG memory area into GPU directly

Given the above and your statement about 10 minutes to generate the DAG it clearly appears your hardware can not efficiently mine ETHASH due to these possible conditions :

1. Very slow memory access on GPU
2. Very slow communication between GPU and CPU (pci bus)
3. Something else is using GPU extensively

**Comment by AndreaLanfranchi** [comment]
The entire process of ethminer is atomic and can't be interrupted unless you kill the whole ethminer process. On very slow cards the actual DAG for Ethereum (2.7Gb) is generated in no more than 20~22 seconds. So your 10 minutes delay depicts a very critical hardware condition.

**Comment by AndreaLanfranchi** [comment]
BTW 
Celeron J1900 are widely used in mining due to it's very low price. GPU mining does not require great CPU powers so your CPU is not to blame for this delay.

**Comment by AndreaLanfranchi** [comment]
I am sorry but you won't get any valuable result with that configuration.

You have to use a dedicated GPU (NVIDIA or AMD)

**Comment by deepline1986** [comment]
Gotcha.
Thanks.
