### ISSUE TITLE
Reading 511 degrees on GPU but card is cool

### ISSUE THREAD

**Issue by reqshark** [ethereum-mining/ethminer#1381]
## `--tstart` and `--tstop` dont work.

ridiculous readings from the gpus, i.e. 511 C temps

<img width="995" alt="screen shot 2018-07-24 at 8 25 32 pm" src="https://user-images.githubusercontent.com/937826/43177987-fd3181ba-8f7f-11e8-8833-36f07a6be06b.png">

**Comment by StefanOberhumer** [comment]
1.) Can you give us your full command line?
2.) Can you add the first lines of ethminer output ? (till it starts mining)
- Seems your cards have problems with the temperature reading (if they are the coolest why you're running at 100% fanspeed)
Nothing else: As your gpus are red (indicates they should be paused) - I'm interested why the still hashing...

**Comment by ddobreff** [comment]
511 indicates PCIe fall,
equivalent to Nvidia GPU fell from pci bus.

**Comment by StefanOberhumer** [comment]
>511 indicates PCIe fall,
equivalent to Nvidia GPU fell from pci bus.

Still interesting why the cards still hashing...

**Comment by AndreaLanfranchi** [comment]
@reqshark 

Please honor some basic rules: 

1. Do not assign such rude titles to your issues
2. Describe your environment with accuracy: are you using AMD (OpenCL) or NVIDIA (CUDA) ?

**Comment by divinity76** [comment]
on Ubuntu 16.04 with amd.com's AMDGPU drivers, 511 degrees celcius happens if the cable connection is broken or unstable.

you can recreate this issue by starting mining, and then dragging out the pci-e riser cable while it's mining.  the temperature reading will be frozen at 511 celcius within a few seconds.

**Comment by reqshark** [comment]
> Do not assign such rude titles to your issues

Ok I agree that was a rude title. I'm sorry @AndreaLanfranchi, won't happen again.

> Describe your environment with accuracy: are you using AMD (OpenCL) or NVIDIA (CUDA) ?

Using OpenCL AMD. 

This was a hardware issue on my end, with PCIE risers potentially being under powered since i was using SATA. So there's probably nothing wrong with the software. 

I think it's interesting that not using --tstart and --stop fixes, and yesterday I incorrectly and probably too rudely blamed them for my lack of hashrate. 

Those two flags are simply responding to the incorrect temp readings from my hardware issue. Actually that indicates the flags are operating correctly based on their input.

**Comment by divinity76** [comment]
@reqshark ah yeah, don't use SATA to power your risers, they can simply draw too much from the cable, to the point where it ruins the PSU. sata-powered risers have ruined 2 PSUs for me (1x chinese noname, and 1x corsair hx1000 )  - ever since, i've use this pci-e splitter to power all my risers: https://www.moddiy.com/products/Bitcoin-Mining-PCI%252dE-6pin-TO-2-PCI%252dE-6%252b2pin-Splitter-Cable.html
 (with the gpu and the gpu's riser sharing the same splitter), works great.

and a warning, if you're gonna use pci-e splitters like me, *don't cheap out*, i did that mistake, i bought some cheaper chinese pci-e splitters earlier, and had lots of problems with them, and opted to replace them all (with the quality splitters from moddiy linked above )

**Comment by divinity76** [comment]
this is what happened to the last PSU i had powering risers by sata:
![img_20180315_094701](https://user-images.githubusercontent.com/1874996/43232313-7fb73418-9070-11e8-83be-0c44f3c691b1.jpg)
![img_20180315_094351](https://user-images.githubusercontent.com/1874996/43232350-af4f4c24-9070-11e8-86ce-704da0279477.jpg)

**Comment by reqshark** [comment]
@divinity76, that's a powerful anecdote, thanks for sharing! 

spec says 12V SATA connections output max 53W.. [check out the spec ](http://www.playtool.com/pages/psuconnectors/connectors.html#sata)

our GPUs are powered both by the PCIE slot and the 6/8pins

therefore, my understanding is that we're gonna have problems when a gpu attempts to draw more power from the riser than the 53Ws spelled out by spec
