### ISSUE TITLE
Multiple instances of Etherminer

### ISSUE THREAD

**Issue by nguylb73** [ethereum-mining/ethminer#181]
Just doing some preliminary research before attempting to use multiple instances of Ethminer. I'm curious if "--no-precompute " is needed on all instances but one, for version 0.11.0 ?  In addition anyone notice any benefits of splitting up your GPUs on multiple instances? I'm going to split mine up to test various pools.

**Comment by Rootax** [comment]
I run one cuda instance and one opencl instance, without --no-precompute , no problem. But I have multiple ethminer.exe files (2, one for each instance).
I though the dag problems with multiple instances were presents when dag were generated on the disk, but since now it's in the vram, is it still a problem ?

**Comment by hcbraun** [comment]
I run one instance of ethminer per card behind eth-proxy. For me this is more stable. If a card crashes because of overclocking. The other instances keep on running. 
Performance might be a bit better. With one instance for all cards, when a solution is found. nvidia-smi shows gpu processing stop on all cards for a moment. With multiple instances you do not have that. 
No idea about precompute. I just run like this:
./ethminer-f99ca9822 -U --cuda-schedule sync -F http://127.0.0.1:8080/card0 --cuda-devices 1
The order of the cards ethminer uses can be different then the one nvidia-smi / nvidia-settings uses.

**Comment by chfast** [comment]
The processing stopping was a feature, but this was addressed in #179 and is available in https://github.com/ethereum-mining/ethminer/releases/tag/v0.12.0.dev1.
