### ISSUE TITLE
Virtual memory usage is extraordinarily high

### ISSUE THREAD

**Issue by geofurb** [ethereum-mining/ethminer#1854]
Running ethminer on Ubuntu 18.04, I'm seeing extraordinarily high virtual memory usage (`VIRT`) in `top` (about 513GB), though resident memory (`RES`) is only 120MB, so this isn't actually being used. What's going on here?

**Comment by MariusVanDerWijden** [comment]
The system reserves some virtual memory for communicating with the GPU, since the DAG files are so big, and you have probably more than 1 GPU in your system, the virtual memory usage is pretty high. However since it does not use it, it can safely be ignored.

https://devtalk.nvidia.com/default/topic/1044446/cuda-programming-and-performance/high-virtual-memory-consumption-on-linux-for-cuda-programs-is-it-possible-to-avoid-it-/

**Comment by bangdracaena** [comment]
me too
