### ISSUE TITLE
EPOCH 288 causes 4gb nvidia 1050ti to fail

### ISSUE THREAD

**Issue by satori-q3a** [ethereum-mining/ethminer#1929]
Once the DAG updated to Epoch 288, nvidia 1050ti 4GB models now fail with mem loading errors of the dag.

Unexpected error CUDA error in func dev::eth::CUDAMiner::initEpoch_internal at line 130 out of memory on CUDA device 07:00.0
Unexpected error CUDA error in func dev::eth::CUDAMiner::initEpoch_internal at line 130 out of memory on CUDA device 03:00.0

Running NVidia 1660ti 6gb models also glitched out with zero hash rates until the miner was shutdown and restarted.  Since then they now behave well, as before.
Both Clayminer and Nanominer are able to load and run with the 1050ti(s).

**Comment by ddobreff** [comment]
ethminer is behaving as supposed, its your OS that allocates more than needed VRAM. Claymore and Nanominer are proprietary miners with additional features that help reducing allocated ram. You have the full power to add this to ethminer code and make other users with similar issue happy :)

**Comment by AndreaLanfranchi** [comment]
@satori-q3a report the output of nvidia-smi **before** launching ethminer

**Comment by satori-q3a** [comment]
C:\Users\satori\Miner>c:\users\satori\miner\miners\ethminer-0.18.x\ethminer --exit --farm-recheck 1000 -U -P stratum+tcp://0xxxxxxxxxxxxxxxxxxxxxxxxx/ename@email.com@eth-us-east1.nanopool.org:9999

ethminer 0.18.2
Build: windows/release/msvc

 i 19:01:22 main     Configured pool eth-us-east1.nanopool.org:9999
 i 19:01:22 <unknown> Selected pool eth-us-east1.nanopool.org:9999
 i 19:01:22 <unknown> Stratum mode : Stratum
 i 19:01:22 <unknown> Established connection to eth-us-east1.nanopool.org  [192.99.69.170:9999]
 i 19:01:22 <unknown> Spinning up miners...
cu 19:01:22 cuda-0   Using Pci Id : 01:00.0 GeForce RTX 2070 (Compute 7.5) Memory : 8.00 GB Grid size : 2,048 Block size : 512
cu 19:01:22 cuda-1   Using Pci Id : 03:00.0 GeForce GTX 1050 Ti (Compute 6.1) Memory : 4.00 GB Grid size : 2,048 Block size : 512
cu 19:01:22 cuda-2   Using Pci Id : 07:00.0 GeForce GTX 1050 Ti (Compute 6.1) Memory : 4.00 GB Grid size : 2,048 Block size : 512
 i 19:01:22 <unknown> Authorized worker 0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/email.com
 i 19:01:22 <unknown> Epoch : 288 Difficulty : 2.23232 = 10.00 Gh
 i 19:01:22 <unknown> Job: 04f60e3a... eth-us-east1.nanopool.org  [192.99.69.170:9999]
cu 19:01:24 cuda-2   Generating DAG + Light : 3.30 GB
cu 19:01:24 cuda-0   Generating DAG + Light : 3.30 GB
cu 19:01:24 cuda-1   Generating DAG + Light : 3.30 GB
cu 19:01:24 cuda-2   Unexpected error CUDA error in func dev::eth::CUDAMiner::initEpoch_internal at line 130 out of memory on CUDA device 07:00.0
cu 19:01:24 cuda-1   Unexpected error CUDA error in func dev::eth::CUDAMiner::initEpoch_internal at line 130 out of memory on CUDA device 03:00.0
cu 19:01:24 cuda-2   Mining suspended ...
cu 19:01:24 cuda-1   Mining suspended ...
 m 19:01:27 <unknown> 0:00 A0 0.00 h - cu0 0.00, cu1 0.00, cu2 0.00
 i 19:01:27 <unknown> Job: c2707248... eth-us-east1.nanopool.org  [192.99.69.170:9999]
 i 19:01:29 main     Got interrupt ...
 i 19:01:29 main     Disconnected from eth-us-east1.nanopool.org  [192.99.69.170:9999]
 i 19:01:29 main     Shutting down miners...
cu 19:01:34 cuda-0   Generated DAG + Light in 10,219 ms. 4.70 GB left.
 i 19:01:34 main     Terminated!

**Comment by AndreaLanfranchi** [comment]
I reiterate @satori-q3a report the output of nvidia-smi before launching ethminer ?

**Comment by satori-q3a** [comment]
C:\Program Files\NVIDIA Corporation\NVSMI>nvidia-smi
Thu Oct 03 23:03:24 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 436.48       Driver Version: 436.48       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2070   WDDM  | 00000000:01:00.0  On |                  N/A |
| 53%   57C    P0    37W / 185W |    748MiB /  8192MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 105... WDDM  | 00000000:03:00.0 Off |                  N/A |
| 39%   47C    P0    N/A /  75W |     78MiB /  4096MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 105... WDDM  | 00000000:07:00.0 Off |                  N/A |
| 32%   42C    P0    N/A /  75W |     78MiB /  4096MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

And task manager's performance info of the gpus show that the 1050ti are not used and not loaded with the display driver overhead.

**Comment by Nreif** [comment]
Hi,
this misbehaviour is due to a bug located in the CUDAMiner.cpp module. Even in version 19.0.
On the image attached you see the problem. When checking for sufficient memory, in the original version the totalMemory is compared with the RequiredMemory. But totalMemory is NOT available memory with is much smaller. So the program does not identify the missing memory on the 1050 ti and tries to load up the DAG what results in running into the subsequent catch block.
I fixed the error by calling the CUDA function cudaMemGetInfo which precisely gives you the memory available and total.
Then I compare the amount of available memory ("CUDAFreeMem" in my variable) with the required one and that comparison correctly identifies the 1050 ti as to having not enough VRAM. As as consequence, the program does not try to load up the DAG later.
By the way, the Claymore miner will fail some Epochs later as well. The only difference is that this miner does not load up the light DAG part into VRAM wich is currently around 55 MB. At the moment where the DAG itself exeeds the available memory, the Claymore miner will fail as well what is already true at the moment I think.
AND: Some websites offer the calculation at which time which card will fail loading the DAG. Most of these are nonsense because they take the total mem (6 GB for example)  as a base for the calculation. The cards will fail much earlier since the mem really available is MUCH less.

![MemFault](https://user-images.githubusercontent.com/45993308/67927094-06507080-fbb8-11e9-8d2f-967f2f90265b.jpg)

**Comment by AndreaLanfranchi** [comment]
Closed via #1998
