### ISSUE TITLE
2 pools or 2 purses in one pool

### ISSUE THREAD

**Issue by progros** [ethereum-mining/ethminer#227]
Is it possible to make the miner work immediately on 2 pools or 2 purses in one pool?

**Comment by jimmykl** [comment]
You can run two different instances with their own file pointing to a different pool/wallet

**Comment by progros** [comment]
I understood it.
I'm interested in a quick launch.
Is it possible to compile ready-made wallets in a miner?
Or in the settings to register 2 purses?

**Comment by jimmykl** [comment]
I can't think of any miner which has setting compiled into it, that would be very inconvenient for most users.

You can set 2 addresses in 2 startup files and just open those. Doesn't take much time to setup or run.

**Comment by progros** [comment]
Well thank you.
And how do I adjust the intensity of production?
For example, that 80% of capacity is extracted on one pool, and on the other 20%.
Tell me please.

**Comment by progros** [comment]
up

**Comment by jimmykl** [comment]
Oh are you thinking about doing this on one card? I can't think of a way to do that sorry, only a per card basis with a rig. Someone else might have an idea.

**Comment by progros** [comment]
No, you do not understand me.
I want to run 2 miners at the same time.
One produces the LBC of another ETH.
Now, at launch, 50% of the power is used by LBC, 50% uses ETH. And I want ETH to use only 20% of the card's power.
Thank you.

**Comment by jimmykl** [comment]
OK so you want to mine 2 different algorithms not 2 different pools/wallets/purses.

This miner only mines ETH at the moment.

There is already an issue requesting dual mining here: #215 please add a comment there and close this one.

You should look at using Claymore in the meantime.

**Comment by progros** [comment]
Claymore is slightly slower.

Is it possible to reduce the intensity of production by this miner?

**Comment by derubm** [comment]
it **IS** actually possible (at least with nvidia cards). (i am not really sure if its worth it)
i tested that with following settings ( ~50 % for each card of hashing power)
result: 1 nvidia gtx 1060:
Scrypt ~280 kh/s
ETH: 12-15 mh /s
GFX Card Settings (Samsung memory)
GPUSpeed: 1700 , Memory: 9400
Power limit:77% (Scrypt neds a lot more power)

ETH:
Software: Ethminer
Settings: `--cuda-parallel-hash 4 --cuda-grid-size 1024 --cuda-block-size 256 -v 6 --cuda-schedule auto`

Scrypt:
Software: CCMINER
Settings:
`	"intensity": 15,
	"algo": "scrypt",

	"launch-config" : "20x24",
	"lookup-gap" : "2",`
![image](https://user-images.githubusercontent.com/6720202/29036870-8bc81cc0-7ba1-11e7-8910-c989522bd0d1.png)
![image](https://user-images.githubusercontent.com/6720202/29036896-a4439176-7ba1-11e7-8786-f7f58941b0fb.png)

**Comment by mreid2005** [comment]
@progros : it helps if Dual Mining is explained, the only time it is profitable to dual mine is when the coin your attempting to mine is compatible with the hash work being down by the primary algorithm So in essence your doing the work once but submitting it to 2 pools.  in theory the only resources consumed then are the transaction with the two pools, and "fixing" the header for each pool there are MUCH better explanations out on the WEB. but that's why trying to split the work between two pools in the manner you describe will never be as efficient.  Claymore's may Mine slightly slower, but realize that if you think there is a profit in dual mining, then his maintains ethereum hashrate and only has a slight hit to your alt coin's mining rate.  (I still prefer this miner, over Claymore's) though I have to use it in the PIMP OS build because it doesn't have an API yet. as soon as it has an API, they will be including it also.  (I'm hoping to be able to contribute sometime soon to the project )

**Comment by progros** [comment]
Share please the link where you can find: how to register the extraction of one coin at the same time for two pools.
I could not find such information anywhere.
Thank you.

**Comment by jimmykl** [comment]
@progros if you cannot follow @derubm's directions or @mreid2005's advice then I think you need to accept that there is no 'pre-made' solution which is going to do what you are asking.
