### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by cnilsecure** [ethereum-mining/ethminer#289]
Can I mine etc with ethminer? or is it only for eth?

**Comment by DDDanny** [comment]
it's named ETHminer - hopefully answered? ;-)

**Comment by rdasx** [comment]
Yes you can mine any ethash coin with ethminer. Just point it at an etc
pool and you'll be good to go.

On Sep 4, 2017 6:08 PM, "DDDanny" <notifications@github.com> wrote:

it's named ETHminer - hopefully answered? ;-)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ethereum-mining/ethminer/issues/289#issuecomment-327037433>,
or mute the thread

**Comment by AndreaLanfranchi** [comment]
Yes ... you can mine ETC and also UBIQ with ethminer.
Already tested and works fine.

**Comment by RGPreisschild** [comment]
@DDDanny wow... fucking troll

_Sent from my UMI PLUS using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by DeadManWalkingTO** [comment]
I think this issue can be closed.
