### ISSUE TITLE
A few thoughts from enduser

### ISSUE THREAD

**Issue by rapra** [ethereum-mining/ethminer#315]
Hello!
Than you for a good work, I would like to share my thougths:
1. displaying hasrate
- display is made to often, each second is to often - it should be 2-3-5 seconds period
- there should be added additional timer for display enabled after generating dag. And then disabled on share found, and enabled again after receiving new job/set work - now it is reading data with no pauses, what causes visible drops on reported hasrate (problem is that hashrate calculator getting time when hashes are not made when new work appears). It will make it more smooth (as claymore miner is with about 5-10 second hasrate report period), and will make better presence for enduser. 
P.S. Now I am testing newest RC3 with patch and it seems that it was inserted in code. If yes, thank you
- there should be added -lowintensity mode, like claymore miner has. I work on pc with a card on which I mining, and with that miner I have 'overloaded pc effect', claymore with lower -ethi option work good (hashrate drop only ocasionally when I make something more intensive) without any discomfort
sincerelly,
- on 0.12 rc2 I had one crash - ethminer stopped working, but I didnt make a screen. Will testing this version now
Radek

**Comment by rapra** [comment]
Just noticed that newest version has high cpu usage, about 50% cpu power usage.
Maybe it is additional problem of that new feature 'smoth timer'?

**Comment by rapra** [comment]
I just tested 0.12 RC3, RC2 and RC1 - all utilises ~50% CPU and overloading windows

**Comment by rapra** [comment]
In comparison, claymore ethminer uses 0-1% cpu

**Comment by mnik247** [comment]
'smoth timer' not present before version 0.12rc3.
I used (in linux) latest git version=0.12rc3. and not fixed more CPU load.
What you set farm-check?

**Comment by rapra** [comment]
hmm, I used default 500 (not set). Now I changed to 3000 and it changed period between new line with hashrate is apearing - thanks, it is much better. Ethminer ig getting 40% when starting, and 50% after less than 1 second of existing on processes list (even on presentation of version etc. uses 50% cpu). I think that there are some timers which making that problem. Claymore miner dont do that way at all.
I would like very much to use this miner, because it is getting similar hashrates with no fee but I must have not overloaded windows to work on my pc.
I use windows 7 64 bit with Core 2 duo 3.16GHz and 8GB RAM.

**Comment by mnik247** [comment]
I used 'farm-check' 10 sec.
More details I posted here:
https://github.com/ethereum-mining/ethminer/pull/303#issuecomment-329101648

**Comment by rapra** [comment]
Thank you, I ended with 5 seconds for now. It is have no effect with cpu overload, there must be something working a lot in background (timer or something), what is disturbing cpu so much.
How did you get those nice coloring in your miner?

**Comment by mnik247** [comment]
You can try 10 sec.
I used my custom build with more "colored" console.

**Comment by rapra** [comment]
Is it possible to you compile that version for me for windows? Maybe it will not freezing?

**Comment by transistorgit** [comment]
After upgrading to 0.12.0rc2 from 0.11 I also recognized a huge CPU load! It's currently 389% on a seasoned quad core i7. 
First line of "top":
top - 22:52:21 up 3 days,  8:15,  1 user,  load average: 17.24, 17.14, 17.04

**Comment by mnik247** [comment]
to @rapra 
Sorry, but I not use Windows now, I switched to Linux and compile Linux version.

**Comment by mnik247** [comment]
to @transistorgit 
Try increase 'farm-check' to 5-10 sec.
I haven't problem with CPU load.

**Comment by rapra** [comment]
Found. I set --cuda-schedule auto - this is causing that cpu overloading. I used that because it stabilizing hashrates on higher values, what is better to observe with less --farm-recheck value (or default). 
Could someone look at code and try repair high cpu usage with --cuda-schedule auto set?

**Comment by transistorgit** [comment]
farm recheck is already 2s. Should be slow enough...

**Comment by rapra** [comment]
OK, tested those options: auto is causing freezing, probably it is setting yield, what set is causing the same freezing effect. When I set to sync, I see higher values appearing sometimes than with spin. Both spin and sync dont freezing windows

**Comment by rapra** [comment]
reassuming: I request to add additional timer for report hashrate, enabled only when it is needed (after dag generation is done), and paused on submitting a job/receiving a job to eliminate errors in calculating hashrate. Now this timer is the same timer which checking a new job, so if I set farm-recheck 10 seconds to not be atacked to often with new lines of text in console, I could lost a lot of seconds when miner dont receive a new job as soon as possible.

**Comment by smurfy** [comment]
> Now this timer is the same timer which checking a new job

only on getwork mode. but i will change that soon.

**Comment by Blacksuu** [comment]
Lower intensity or gpu usage yup that it will be a good new feature to be implement special for ppls with 1 video card who want to mine & use pc for other purpes
@rapra i think you want to be implement from claymore -li function (low intensity mode. Reduces mining intensity) with have more impact on gpu usage vs -ethi function Ethereum intensity
About cpu usage on my side windows 7 ethermine = 0% with noo spike (task manager or process explorer same thing)

**Comment by rapra** [comment]
I am using not -li but - ethi, because I dont use dual mining (it overloading windows, on wich I want to work when mining) - probably it is the same function. I also use -lidag (lower intensity in dag generation), I dont know that it really works, but I suppose it causing a bit less freezing on miner starting.
Now afre the tests, I ended with options:
--farm-recheck 3000 - comfortable enough (hope that timer for measuring and displaying harhrate will be introduced apap, to not decreasing earnings due to less active new job checking with no-default recheck value)
--cuda-schedule sync - it causing normal cpu using (auto, yield and spin are giving ~50% cpu usage), but any option is giving as comroftable desktop usage as claymore with -li option

**Comment by Blacksuu** [comment]
about decreasing earning or income till now all it have from each pool 1 important value to check > Average Hashrate < if that value is nearly same was before rc3 is best prof to undestend for all not losing anything
p.s. Average Hashrate value after a long run like 12-24 hour run is most acurate value what count because it is generate base on your **effective work on pool** & not only by a displayed value

**Comment by rapra** [comment]
@Blacksuu please keep in mind, that I dont have a rig which is mining with any bother from user for hours - I have pc with gpu what is mining when I work. So your proposal of measuring procedure is useless for me. In my case I need / must measure for a short time with more probes in time span - in practice I observe values apearing in console and see what values are apearing which values are often. In this miner I must ignore first 2-3 values after getting new job, when 'bug' of hashrate calculate function is present, next values are quite stable and repetitable. With those conditions accurate measurement is absolutely possible

**Comment by smurfy** [comment]
> I must ignore first 2-3 values after getting new job

are you using opencl or cuda?  If cuda, we are thinking about adapting the changes of #217 for it. This could improve that. But yea, with cuda i see the dip on new job. 215 vs 219 sometimes even 200.

**Comment by rapra** [comment]
GTX1060 - CUDA.
Function counting current hashrate has an error. It counts all time. When miner is sending a share or getting a new job, it is not counting. In that case number of shares is decreased, then division number_of_shares/time is less than should be. It provides hashrate distortions (on console screen and probably reported to pool too).
A fix I proposed is: on events like share_found, new_job_found, dag_generation_pending, connection_error and similar program must stop hashrate calculator timer, and start it again after procedures responding to those events. It will eliminate problem and we could step to finding other problems

**Comment by smurfy** [comment]
Hm regarding the events:
* share_found
Is handled async, also it could happen, that multiple shares are found before pool sends new data.
so the GPU's are not interrupted and calculating full speed. so no timer stop needed here
* new_job_found
On new job (work update), i noticed on one GPU i do not have any dips in hashrate, with 7 GPUs, i do. So maybe since the hash-count will already reset once new work arrives, it could really make sense to reset the time here too. (will do some tests). 
* dag_generation_pending + connection_error
I did not look at the code but my guess is on both events the GPU threads will be stopped.
But i need to check if hashcount gets reset on stop too. The new collect Hashrate method (the timer)  Only uses global hashrates > 0. So if the hashcount dropps to zero, it will not be count or cause a dip in the hashrate display.

**Comment by rapra** [comment]
- new_job_found
please leave default farm-recheck option (500ms), let only 1 gpu to mine and observe hashrate, it is dropping just after new job (or maybe set work) event. It is reapeatable and significant

- hashrate
I am really sure, that somehow displayed hashrate is dropping just after reveived new job/set work information. In my opinion it is caused by wrong hashrate calculate function what should be resetted on this event or should include conditions for discontinued work on gpus (IMO easier should be just reset timer = stop, reset values, start again).
I cant include screen in this message, but on screen I have values: 23.97, 22.93, 23.97, 22.93, 23.97, 22.93, received new job..., set work..., 15.83, 22.93, 23.97, 22.93, 23.97

**Comment by Blacksuu** [comment]
@rapra you say you have 1060 perfect i have exact same one single diference between me & you is i have 2 gpu in system: 1. 1060 what is mining only 24/24 & 2. one old 650 gtx use for my own necessity soo i will post print screen done with rc3

GPU 1060 > --farm-recheck 10000 = max hrate value is 24.9
Claymore = max hrate value 25.2
windows 7 / power limit 65 / Core clock +50 / Vram Clock +930
- condition how i run "-U -SP 1 -RH --cuda-devices 0 --cuda-grid-size 4096 --farm-recheck 10000"
p.s. --farm-recheck 10000, 5000, 3000, 2000, 1000, 500 or 200 it will bring same displayed max value after fix with rc3 aka #303 before that displayed value was all over the place

[Imgur](https://i.imgur.com/18jqqFO.png)

**Comment by rapra** [comment]
I really tried to explain, that error is visible when you leave farm-recheck default (default = 500 = 0.5sec). If you measure a long time (10 sec), that drop will not be noticable. But it is not proving that error not exists in your settings, really

**Comment by derubm** [comment]
to get the real hashrate ( not the theoretical one ) just use a simple formula:
hashesPerSecond = math.pow(2, 32) * proofsOfWork / secondsElapsed
that way you can calculate the hashes per timeframe ( for example 15 minutes ).
***proofsofwork beeing Diff 1 shares. Depending on miner diff you need to multiply / divide that ofc.

**Comment by rapra** [comment]
you are right
- poolside
for example ethpool is just reading hashrate reported by miner. Whe I used ethminer 0.11 without hashrate reporting, ethpool statistics didnt show hashrate. On the other side  ethpool stats were very innacurate (a long time there was an annoucement that 'they know problem')
-  hashrate
I know how to calculate hashrate (I wrote hashrate calculator in php/js), hashrate could be calculates as well in long period and as in short period, the only thing we need is adequate measuring instrument accuracy (I am also an engeneer, so we really could discuss about it)
I dont know why I cannot add picture to post "Something went really wrong, and we can’t process that file"

**Comment by transistorgit** [comment]
Update on CPU load:
rc2 crashed my rig tonight because of cpu overheat, it had nearly 100% CPU load on ethminer process.
now updated to rc3, CPU load is back to ~1%, without changing anything else.

(running linux)

**Comment by Blacksuu** [comment]
i confirm using --cuda-schedule it can cause CPU usage aka simple test:
ethminer -U -M 141 --cuda-devices 0 --cuda-schedule <insert option>
option = auto, spin, yield or sync
a. --cuda-schedule auto, spin or yield => result CPU 25%
b. --cuda-schedule sync noo CPU usage - 0%

**Comment by rterbush** [comment]
Confirming very high CPU load when using `--cuda-schedule`

compiling from master branch, e27a962

**Comment by dougbacelar** [comment]
Tried to mine eth for the first time using this miner with the following code in a .bat script:

```setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
ethminer.exe --farm-recheck 200 -G -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -v 1 -O <Ethereum_Address>.<RigName>
```

CPU overloaded and restarted my Rig twice, reached temperatures of over 100C.

I am back to zCash mining for the time being. My CPU stays at a stable 40C while mining zCash.

**Comment by bmatthewshea** [comment]
@dougbacelar Try using -U/Cuda for nvidia cards

**Comment by dougbacelar** [comment]
@bmatthewshea thanks! I dont understand why, but it worked 👍 💯

**Comment by bmatthewshea** [comment]
Yeah think it's known issue right now (other issues here). If using cuda, you may even get slightly better hashing, too.  I do.

**Comment by paucoma** [comment]
First of all, sorry for the long post but I'm trying to include as much info as I believe could be relevant to be able to help both developers and users. I've been reading in several places that every one recommends the settings:
```
setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
```
I have not set any of these variables yet as I have not completely understood what they actually do.

Asus Prime Z270-A, Intel Core I7-7700, 16GB DDR4 RAM, 2x Asus Dual GeForce GTX 1070 (Micron Memory, PState:2, -200 GPU +333 Mem PwrTgt 70%), Windows 10 ver 1709, ethminer-dbg-0.12.0-Windows

Running ethminer with : `ethminer.exe --cuda --farm <dwarfpool>`
And getting approx 58 MH/s 

Found Definition: `GPU_FORCE_64BIT_PTR [0 | 1]` – When set to 0 this setting allows access to 32-bit address space of memory ~3.8 GB.
When set to 1 it allows access to 64-bit address space. 
While it may sound like a good idea to set it to 1, it may actually hurt performance since then pointer access would require twice the number of clock cycles to complete than it would if left in 32bit mode. 

**Question: the current DAG is 2.3 GB or so in size, so this should currently not improve mining, probably slow mining down. Correct?**

Found Definition: `GPU_MAX_HEAP_SIZE [0 – 100] `– By default the memory made available to OpenCL is limited to just 50% of total GPU memory. 
With this setting it is possible to increase the amount of memory available up to 100% 

**Question: is this relevant to CUDA mining aswell? And if so, would only be necessary if the DAG is larger than half of your GPU memmory, no? So currently GPUs with 6GB or 8GB would not notice a difference. Anyone with a 3GB or 4GB Nvidia GPU mining in --cuda can confirm this?**

Found Definition: `GPU_USE_SYNC_OBJECTS [0 | 1]` – Syncs the System CPU with the GPU actions to improve performance, 
0 is thought to lock usage to a single CPU core while 
1 is thought to allow access to multiple CPU cores. 

**Question: Since Memory mining algorithms theoretically should have low CPU usage anyway, why should this influence mining?** Would be interested in knowing what the "default" or my current setting is, 

Found Definition: `GPU_MAX_ALLOC_PERCENT [0 – 100]` – Maximum amount of memory that can be allocated globally.  Needs to be equal to or higher than the GPU_SINGLE_ALLOC_PERCENT setting.

Found Definition: `GPU_SINGLE_ALLOC_PERCENT [0 – 100]` – Maximum amount of memory that can be allocated to a single process. This is limited by the GPU_MAX_ALLOC_PERCENT setting, so be sure to increase both.

**Comment: Would be interested in knowing how to find out what the current values are, Anyone know where/how to find them? Or is it just ( if def <VARIABLE> then x else y ) ?**

**Comment by paucoma** [comment]
Aha, thanks for the input, I have tried setting some of these variables using **set** instead of **setx** and have not noticed a significant difference on my setup. 
I had asked a user of a GTX960 with 4GB memory to do a couple tests with changing the `GPU_MAX_HEAP_SIZE` to 50% and 100%, and also trying to mine using OpenCL and CUDA, In all cases they managed to successfully load the DAG and start mining. there appeared to be a slight difference in Mining speed (1MH/s) but there were too few data points to confirm. In any case I wase looking to see if the DAG coud be created or not. So did not influence that nVidia Card, niether does it influence my GTX1070.

**Comment by bmatthewshea** [comment]
@paucoma Best to use -U/--cuda on NV cards. 
You may notice increased CPU use if using OpenCL for NV cards. (known issue)
I also tend to get a -slightly- better hashrate using cuda. This may be the reason behind the difference you see.

**Comment by abonander** [comment]
Second the low intensity feature, maybe through a "hashrate target" where the miner actually reduces the submission rate of work if above the target. Then the user can set the target to a fraction of their maximum observed hash rate to get approximately that fraction of GPU usage.

**Comment by DeadManWalkingTO** [comment]
GTX1060 +150/+500/65%TDP @ 23-24MHs

1. Try Update Drivers.
Download and install the latests.

2. Try Update Ethminer.
Download (or beter build) the latest.

3. Try use -U for CUDA devices.
Test launch command:
`ethminer -RH -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.test`

4. Try to change P2 State and Power managment mode.
You can use [NVidiaProfileInspectorDmW](https://github.com/DeadManWalkingTO/NVidiaProfileInspectorDmW).
For the best mining hashrate choose from sector "5 - Common":
    - CUDA - Force P2 State (Set to "Off")
    - Power managment mode (Set to "Prefer maximum performance")

5. Try Tweak Win10.
You can use [Windows10MiningTweaksDmW](https://github.com/DeadManWalkingTO/Windows10MiningTweaksDmW) (#695).

6. Try Optimize/Overclock GPUs. 
You can use [MSI Afterburner](https://www.msi.com/page/afterburner) for GPU OverClock/Optimize. 

7. Try use a WatchDog
You can use [ETHminerWatchDogDmW](https://github.com/DeadManWalkingTO/ETHminerWatchDogDmW) (#735).

Please feedback.
Thank you!

**Comment by AndreaLanfranchi** [comment]
Many (if not almost all) of the points are out-of-date or already addressed.
It remains the problem of "Low Intensity Mode" for which I invite to express a vote on the relative poll #1063 
This gets closed.
