### ISSUE TITLE
"ethminer stopped working" - How to close it without the question?

### ISSUE THREAD

**Issue by Simon0Harms** [ethereum-mining/ethminer#362]
I  don't know how this is called in english, but i hope you know it if you see the window...
![eth clsoe unexpe](https://user-images.githubusercontent.com/10880193/32141942-c7cc5e76-bc8c-11e7-9594-b0631a3d0c3b.png)

The Miner is startet with the task scheduler.
The task task scheduler looks every 5 Minute if the program is currently running, if not he starts the miner.
But when i get the message from above the task scheduler thinks that the program is currently running and don't restart the miner. How can i close the program when i get the error?

**Comment by Simon0Harms** [comment]
Ok, i hope this will solve my problem:
https://www.raymond.cc/blog/disable-program-has-stopped-working-error-dialog-in-windows-server-2008/

**Comment by MariusVanDerWijden** [comment]
Do you use an Antivirus? 
Mining is way easier on Linux

**Comment by Simon0Harms** [comment]
@MariusVanDerWijden 
I use only the Windows Defender.
I would use Linux (I hate Windows), but i didn't found a solution to change the mem clock for my vega56...

Because of vega56 i switched from Linux to Windows...

**Comment by MariusVanDerWijden** [comment]
https://www.phoronix.com/scan.php?page=news_item&px=AMDGPU-OverDrive-Support
Have you tried this?

**Comment by Simon0Harms** [comment]
Thats what i heard:
https://forum.ethereum.org/discussion/comment/83479/#Comment_83479

**Comment by DDDanny** [comment]
Hi Simon, 
thanks for the setting, I guess this will work. I have had no problems yet but who knows... 

I remember when adjusting to much overclocking _while the ethminer is running then it crashed_ 
Maybe also helpfull for you: In #328 @orkblutt mentions to use [MinerLamp](https://github.com/orkblutt/MinerLamp) - I guess this will also aviod the popup and can restart the miner.

I check the ethminer process and also MSI afterburner via a powershell script every 60s if they are in "not responding state" or if a  CUDA error occured -> the miner is killed and restarted - there is no windows popup or at least it does not have to be confirmed...
if MSI stops working system reboots... if any windows system log NVIDIA display warnings or errors occur -> system reboots...

With a "stable" OC "only" the display driver crashes typically only on each DAG generation (but not ethminer) but is fine after system reboot. [even if windows has to be rebooted once a day due to dispaly error it gets me 2mh/s more including the 1 minute reboot time]

B.R.
Danny

**Comment by Simon0Harms** [comment]
@DDDanny 
I am waiting for a AMD Version:
https://github.com/orkblutt/MinerLamp/issues/42

Since i changed the setting everything works fine.
I didn't even noticed if the miner crash.
One processes worked for 10h now, the other one for 22h.

If it crash, the window  didn't pop up and the programm will closed completly.
The task sheduler will check every 5 Minutes if the process is up. If not he will start the process
