### ISSUE TITLE
AMD RX 480 optimazation flags needed

### ISSUE THREAD

**Issue by nerle** [ethereum-mining/ethminer#380]
Hello,

with the current AMD driver 17.11 (Windows) I get around 20 M/hs. Any flags needed to get the 24-25 M/hs I read at different websites? 

best regards Dirk

**Comment by derubm** [comment]
Most people have to flash the GPU bios to get those speeds on AMD cards.

**Comment by smurfy** [comment]
As @derubm mentioned, to get 28-32 MHs on AMD Cards you need to:
* Overclock your card (memory, core is not that important, should be around 1100 for core and 1900-2100 for memory), how much depends on memory type
* Mod Bios (very important, patch driver on windows to work with modded bios)

Since everything is really not related to ethminer i close the issue
