### ISSUE TITLE
Ubuntu 17.10 Installation Guide for AMD

### ISSUE THREAD

**Issue by Linuxnoob84** [ethereum-mining/ethminer#393]
Hello,
Iam looking for a Linux installation guide for ethminer.

AMD Card, ethermine Pool.

Thx a lot (Iam Linux noobie)

**Comment by fhlfibh** [comment]
AFAIK there's no "installation".
Download the latest linux release from here https://github.com/ethereum-mining/ethminer/releases/latest
Then start it e.g. as shown on ethermine.org:
```
ethminer --farm-recheck 200 -G -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O <Your_Ethereum_Address>.<RigName>
```
`ethminer -h` will show all available options.

**Comment by Linuxnoob84** [comment]
But where should I type this into?
On Win I used a batch file...

**Comment by fhlfibh** [comment]
@Linuxnoob84 in console or terminal emulator (`gnome-terminal` or something, I don't know what exactly they put in Ubuntu now).

Start that terminal emulator.

Download the release from above: `wget https://github.com/ethereum-mining/ethminer/releases/download/v0.12.0/ethminer-0.12.0-Linux.tar.gz`

Extract the miner: `tar --extract -f ethminer-0.12.0-Linux.tar.gz`

Check the miner: `./bin/ethminer -h` -- it should show you the list of options.

If it does -- start the miner: `./bin/ethminer --farm-recheck 200 -G -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O <Your_Ethereum_Address>.<RigName>`

**Comment by Linuxnoob84** [comment]
it says no OpenCL Platforms found

**Comment by MariusVanDerWijden** [comment]
Can you paste the result of this command 
`lspci | grep -i --color 'vga\|3d\|2d'`

**Comment by stusona** [comment]
I'm attempting to do (almost) the same thing, and I'm running into the same issue: no opencl platforms found.

Here's my output from the command `lspci | grep -i --color 'vga\|3d\|2d'`

`01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Cayman LE GL [FirePro V5900]`

However, after installing fglrx-core_15.302-0ubuntu1_amd64.deb from a [community.amd.com post](https://community.amd.com/thread/202821), my output after running ethminer is as follows:

```~$ ./ethminer 
modprobe: FATAL: Module fglrx not found in directory /lib/modules/4.10.0-40-generic
Error: Fail to load fglrx kernel module!
Error! Fail to load fglrx kernel module! Maybe you can switch to root user to load kernel module directly
modprobe: FATAL: Module fglrx not found in directory /lib/modules/4.10.0-40-generic
Error: Fail to load fglrx kernel module!
Error! Fail to load fglrx kernel module! Maybe you can switch to root user to load kernel module directly
modprobe: FATAL: Module fglrx not found in directory /lib/modules/4.10.0-40-generic
Error: Fail to load fglrx kernel module!
Error! Fail to load fglrx kernel module! Maybe you can switch to root user to load kernel module directly
No GPU device with sufficient memory was found. Can't GPU mine. Remove the -G argument```

**Comment by MariusVanDerWijden** [comment]
FirePro V5900 only has 2GB of graphic memory, you need at least 3gb to mine ethereum
http://www.amd.com/en-gb/products/graphics/workstation/firepro-3d/5900
https://investoon.com/tools/dag_size

**Comment by ddobreff** [comment]
16.04LTS doesn't support fglrx driver. Use amdgpu or radeon instead. AFAIK radeon module isn't suitable for mining.

**Comment by stusona** [comment]
Ah! The 2 GB card is what's killing me.

I'll mine Monero. Thanks all!

**Comment by EoD** [comment]
Can this issue be closed? Or is there an open task to improve documentation?

**Comment by MariusVanDerWijden** [comment]
https://github.com/ethereum-mining/ethminer/issues/449

**Comment by android-dep** [comment]
@ddobreff this is true, fglrx hasn't been used for AMD since 15.04LTS.  It's replacement is ROCm kernel that helps improve mining but it's not necessarily always required to be installed to be able to mine. The most important first step to installing AMD drivers on Linux should be installing these drivers
[AMDGPU-Pro 17.40 Linux drivers](http://support.amd.com/en-us/kb-articles/Pages/AMDGPU-PRO-Driver-for-Linux-Release-Notes.aspx)

The AMD article on that page covers the steps to install those drivers properly, my only suggestion would be to install the drivers from the page with the "./amdgpu-pro-install --opencl=rocm" if you have a Vega10 or newer graphics chipset or "./amdgpu-pro-install --opencl=legacy" for graphic chipsets before Vega10...

- reboot
- then make sure you are in the "video" group by adding your user with this command "sudo usermod -a -G video $LOGNAME" 
- reboot
- then install the opencl-headers needed for miners with this "sudo apt-get install opencl-headers" and then profit

**Comment by DeadManWalkingTO** [comment]
Linux Auto Download/Build Ethminer Script
```
#Download ethminer
git clone https://github.com/ethereum-mining/ethminer.git
#Enter Project Directory
cd ethminer/
#Make Build Directory
mkdir build
#Enter Build Directory
cd build/
#CMAKE
echo "Build"
cmake .. -DETHASHCUDA=ON -DETHASHCL=ON -DETHSTRATUM=ON -DAPICORE=ON
#Build
echo "Release"
cmake --build . 
echo "End Build-Release"
#Enter Home Directory
cd ~/
#End
```

**Comment by BobDodds** [comment]
cmake .. -DETHASHCUDA=ON

?

Is that still for AMD gpu's, and if so what do we have to do to install cuda for linux? I'm researching how to get my amd rx 580's up on msi intel i8 board. I have atiflash, can get the msi bios flash to work from usb drive without windows by using bios, and it appears I have to have old ubuntu 16.04.3 androld amd pro 16.40. uefi is easy with grub2 not refind--refind won't boot install iso's grub2 will--easy--grub2 is easier than refind if refind can't even boot install iso. So, cuda for amd, not just nvidia? Prereq cuda and opencl?

**Comment by BobDodds** [comment]
To the moderators, this thread is still current because of strange situation of 2017 and Ubuntu 16.04.3 being current in 2018 and so howto still most thorough right here as far as how to get up and running in April 2018 on Ubuntu. After this, then people can look at strapping and bios upgrade and uefi and headless setup for remote login--trick to learn there is some people can keep gpu's from bonking on remote login by only issuing remote commands, a lighter light touch on resources.

This is linux, we should be killing it, but we're in Ubuntu 16.04.3 and last years' AMD PRO? I read something about latest kernel having some amd gpu stuff, but not dedicated blockchain only gamer, right? Duh. We're back in 2017 beta amd blockchain. I also have a whine about not being able to simply search either websearch or on amd about current exact amd pro beta fkn driver--why do I have to search and figure out which is the latest **FORUM** post latest amd pro blockchain driver? Not too linuxy, we rock and rule, wtf?

**Comment by BobDodds** [comment]
..we're actually at amd pro 17.50 but that's not real easy to discover.
