### ISSUE TITLE
does not appear to contain CMakeLists.txt

### ISSUE THREAD

**Issue by Arrashg** [ethereum-mining/ethminer#394]
ethminer@ethminer-System-Product-Name:~$ mkdir build; cd build
mkdir: cannot create directory ‘build’: File exists
ethminer@ethminer-System-Product-Name:~/build$ cmake ..
CMake Error: The source directory "/home/ethminer" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
ethminer@ethminer-System-Product-Name:~/build$ 

Can't seem to get passed this part. I looked in the ethminer folder and I DO have the CMakeLists.txt file in there.
![screenshot from 2017-11-21 22-54-40](https://user-images.githubusercontent.com/20796673/33112174-0c70f28c-cf0f-11e7-88e2-967e845991db.png)

**Comment by chfast** [comment]
You are in the wrong dir.

**Comment by Arrashg** [comment]
@chfast Could you please elaborate?

**Comment by chfast** [comment]
You must be in `/home/ethminer/ethminer` dir not `/home/ethminer`.

**Comment by MeqdadDarweesh** [comment]
What about Windows 10?
I'm in the folder which I download it from the official website and the same error message appears!

**Comment by MeqdadDarweesh** [comment]
Ok, I solved that with OpenCV in win 10
it's in sources folder

**Comment by MeqdadDarweesh** [comment]
@niranjanreddy891 
Try with this link, it could be useful for your case.
https://cmake.org/Wiki/CMake/Tutorials/How_to_create_a_ProjectConfig.cmake_file

My problem was with openCV library.

**Comment by niranjanreddy891** [comment]
Thanks for the response @MeqdadDarweesh . I already tried the link you mentioned, but still i am facing the same issue.

**Comment by smurfy** [comment]
Please try the following:

Linux:
````
git clone https://github.com/ethereum-mining/ethminer.git
cd ethminer
cmake -DETHASHCL=ON -DETHASHCUDA=ON -DAPICORE=ON -H. -Bbuild
cmake --build build --config Release
````

Windows VS 2017:
````
git clone https://github.com/ethereum-mining/ethminer.git
cd ethminer

set PATH=%PATH%;"c:\Program Files\CMake\bin"
cmake -G "Visual Studio 15 2017 Win64" -Tv140 -H. -Bbuild -DETHASHCL=ON -DETHASHCUDA=ON -DAPICORE=ON
cmake --build build --config Release
````

Windows VS 2015:
````
git clone https://github.com/ethereum-mining/ethminer.git
cd ethminer

set PATH=%PATH%;"c:\Program Files\CMake\bin"
cmake -G "Visual Studio 14 2015 Win64" -H. -Bbuild -DETHASHCL=ON -DETHASHCUDA=ON -DAPICORE=ON
cmake --build build --config Release
````

**Comment by niranjanreddy891** [comment]
@smurfy. I couldn't understand the link which you mentioned. Can you elaborate it. Also I am using visualstudio 2013.

**Comment by askunix** [comment]
![image](https://user-images.githubusercontent.com/32216117/50507009-8dbfe580-0ab6-11e9-9ff9-a8cb8b6d4702.png)

Could you please elaborate? cmake install already.

**Comment by hackmod** [comment]
@askunix // Please see https://github.com/ethereum-mining/ethminer/issues/394#issuecomment-368547828

**Comment by lisawebcoder** [comment]
this doesnt work for linux
it says errors not complete
and then the last command it doesnt even find the file
wyv

Lisa

**Comment by 62f** [comment]
Which instruction for Linux did you mean by "it", and what is the name of the file which 'it' "cannot even find"? Meaning to elaborate by posting both the command plus its error message.
Such generalizations aren't helpful.

**Comment by lisawebcoder** [comment]
hello thank you for taking the time to reply
this was over 8 months ago and i dont recall exactly the error i got cuz i am not working on this now anymore
however the "it'  for sure i was referring to the terminal in ubuntu 12 or 14 or 16 or 18 and i must of got errors running the commands in the tutorial sorry for now thats what i  recall and i must have been referring to my run file which is supposed to be genereated after running Cmake
i was able to use Make instead of Cmake in my software and get my code to run on ubuntu 14 
and thats why i did not continue with trying to build and run my C++ software with Cmake but just Make

bascally in my root project folder on ubuntu 14 at the terminal

make -j 4
this runs on 4 cores of cpu
then after my software is built

./gb -d

this runs my server at port 8000
and i open a webpage at the IP address of my webhost or localhost such as

localhost:8000
or live
192.169.44.33:8000 (example only)
or with a domain
run.ca:8000 (example only)

for awhile i couldnt get my C++ code to work
and so i tried Cmake
but then i realized my code worked on Ubuntu14 only for now
and i have to fix updates for versions Ubuntu 16 or 18 or 20 etc.


LISA
