### ISSUE TITLE
OpenCL Error (clEnqueueNDRangeKernel)

### ISSUE THREAD

**Issue by Isengo1989** [ethereum-mining/ethminer#401]
GPU GeForce GTX 1050 Ti
Total Memory: 4096MB

```
root:~/Downloads/bin$ ./ethminer -G -M
  ℹ  17:52:51|ethminer  Found suitable OpenCL device [ GeForce GTX 1050 Ti ] with 4226547712  bytes of GPU memory
Benchmarking on platform: CL
Preparing DAG for block #0
 cl  17:52:51|cl-0      No work. Pause for 3 s.
Warming up...
 cl  17:52:54|cl-0      New work: header #50c856ae… target 0000000000000002000000000000000000000000000000000000000000000000
 cl  17:52:54|cl-0      New seed #00000000…
 cl  17:52:55|cl-0      Platform: NVIDIA CUDA
 cl  17:52:55|cl-0      Device:   GeForce GTX 1050 Ti  / OpenCL 1.2 CUDA
 cl  17:52:55|cl-0      Build info: 

 cl  17:52:55|cl-0      Creating light cache buffer, size 16776896
 cl  17:52:55|cl-0      Creating DAG buffer, size 1073739904
 cl  17:52:55|cl-0      Loading kernels
 cl  17:52:55|cl-0      Writing light cache buffer
 cl  17:52:55|cl-0      Creating buffer for header.
 cl  17:52:55|cl-0      Creating mining buffer
 cl  17:52:55|cl-0      Generating DAG
 cl  17:52:56|cl-0      DAG 0 %
 cl  17:52:57|cl-0      DAG 6 %
 cl  17:52:57|cl-0      DAG 12 %
 cl  17:52:58|cl-0      DAG 18 %
 cl  17:52:59|cl-0      DAG 25 %
 cl  17:52:59|cl-0      DAG 31 %
 cl  17:53:00|cl-0      DAG 37 %
 cl  17:53:01|cl-0      DAG 43 %
 cl  17:53:02|cl-0      DAG 50 %
 cl  17:53:02|cl-0      DAG 56 %
 cl  17:53:03|cl-0      DAG 62 %
 cl  17:53:04|cl-0      DAG 68 %
 cl  17:53:04|cl-0      DAG 75 %
 cl  17:53:05|cl-0      DAG 81 %
 cl  17:53:06|cl-0      DAG 87 %
 cl  17:53:06|cl-0      DAG 93 %
 cl  17:53:06|cl-0      Switch time 14868 ms / 11868682 us
Trial 1... 8912896
Trial 2... 9739559
Trial 3... 10175257
Trial 4... 11225375
Trial 5... 11330285
  ✘  17:53:22|cl-0      OpenCL Error: clEnqueueNDRangeKernel -52
min/mean/max: 8912896/10276674/11330285 H/s
inner mean: 10380063 H/s

```

**Comment by ZelimDamian** [comment]
+1

**Comment by basti0001** [comment]
I face the same issue. console says:

./ethminer -G -M
  ℹ  15:11:02|ethminer  Found suitable OpenCL device [ GeForce GTX 770 ] with 4232183808  bytes of GPU memory
  ◇  15:11:02|ethminer  #00004000…
Benchmarking on platform: CL
Preparing DAG for block #0
 cl  15:11:02|cl-0      No work. Pause for 3 s.
Warming up...
 cl  15:11:05|cl-0      New work: header #50c856ae… target 0000000000000002000000000000000000000000000000000000000000000000
 cl  15:11:05|cl-0      New seed #00000000…
 cl  15:11:06|cl-0      Platform: NVIDIA CUDA
 cl  15:11:06|cl-0      Device:   GeForce GTX 770  / OpenCL 1.2 CUDA
 cl  15:11:06|cl-0      Build info: 

 cl  15:11:06|cl-0      Creating light cache buffer, size 16776896
 cl  15:11:06|cl-0      Creating DAG buffer, size 1073739904
 cl  15:11:06|cl-0      Loading kernels
 cl  15:11:06|cl-0      Writing light cache buffer
 cl  15:11:06|cl-0      Creating buffer for header.
 cl  15:11:06|cl-0      Creating mining buffer
 cl  15:11:06|cl-0      Generating DAG
 cl  15:11:07|cl-0      DAG 0 %
 cl  15:11:09|cl-0      DAG 6 %
 cl  15:11:10|cl-0      DAG 12 %
 cl  15:11:11|cl-0      DAG 18 %
 cl  15:11:12|cl-0      DAG 25 %
 cl  15:11:13|cl-0      DAG 31 %
 cl  15:11:14|cl-0      DAG 37 %
 cl  15:11:15|cl-0      DAG 43 %
 cl  15:11:16|cl-0      DAG 50 %
Trial 1...  cl  15:11:17|cl-0      DAG 56 %
 cl  15:11:18|cl-0      DAG 62 %
 cl  15:11:19|cl-0      DAG 68 %
0
Trial 2...  cl  15:11:20|cl-0      DAG 75 %
 cl  15:11:21|cl-0      DAG 81 %
 cl  15:11:22|cl-0      DAG 87 %
0
Trial 3...  cl  15:11:23|cl-0      DAG 93 %
 cl  15:11:23|cl-0      Switch time 21543 ms / 18543474 us
11545881
Trial 4... 12768314
Trial 5... 13177167
  ✘  15:11:32|cl-0      OpenCL Error: clEnqueueNDRangeKernel -52
min/mean/max: 0/7498272/13177167 H/s
inner mean: 12497120 H/s

4GB GTX 770 should be ok. RAM of Plattform is 4GB. debian strech distro. Here additional information:

./ethminer --version
ethminer version 0.13.0.dev0
Build: Linux/g++/Release

git show
commit db253adf453ab8a55c9a288074a21b3de8269e7a
Merge: 6f28ec56a 95417297a

nvidia version
NVIDIA-SMI 375.82                 Driver Version: 375.82 

Does anyone have an idea where this comes from? google is not really helping due to this error code.

**Comment by Hiram-Silvey** [comment]
Ditto! I am on Arch Linux 64-bit with GTX 1070 8GB GPU Memory. Here's my output:

ethminer -M -G
  ℹ  21:15:53|ethminer  Found suitable OpenCL device [ GeForce GTX 1070 ] with 8504868864  bytes of GPU memory
Benchmarking on platform: CL
Preparing DAG for block #0
 cl  21:15:53|cl-0      No work. Pause for 3 s.
Warming up...
 cl  21:15:56|cl-0      New work: header #50c856ae… target 0000000000000002000000000000000000000000000000000000000000000000
 cl  21:15:56|cl-0      New seed #00000000…
 cl  21:15:56|cl-0      Platform: NVIDIA CUDA
 cl  21:15:56|cl-0      Device:   GeForce GTX 1070  / OpenCL 1.2 CUDA
 cl  21:15:56|cl-0      Build info: 

 cl  21:15:56|cl-0      Creating light cache buffer, size 16776896
 cl  21:15:56|cl-0      Creating DAG buffer, size 1073739904
 cl  21:15:56|cl-0      Loading kernels
 cl  21:15:56|cl-0      Writing light cache buffer
 cl  21:15:56|cl-0      Creating buffer for header.
 cl  21:15:56|cl-0      Creating mining buffer
 cl  21:15:56|cl-0      Generating DAG
 cl  21:15:57|cl-0      DAG 0 %
 cl  21:15:57|cl-0      DAG 6 %
 cl  21:15:57|cl-0      DAG 12 %
 cl  21:15:58|cl-0      DAG 18 %
 cl  21:15:58|cl-0      DAG 25 %
 cl  21:15:58|cl-0      DAG 31 %
 cl  21:15:59|cl-0      DAG 37 %
 cl  21:15:59|cl-0      DAG 43 %
 cl  21:15:59|cl-0      DAG 50 %
 cl  21:15:59|cl-0      DAG 56 %
 cl  21:16:00|cl-0      DAG 62 %
 cl  21:16:00|cl-0      DAG 68 %
 cl  21:16:00|cl-0      DAG 75 %
 cl  21:16:01|cl-0      DAG 81 %
 cl  21:16:01|cl-0      DAG 87 %
 cl  21:16:01|cl-0      DAG 93 %
 cl  21:16:01|cl-0      Switch time 8578 ms / 5578357 us
Trial 1... 26913450
Trial 2... 26913450
Trial 3... 26913450
Trial 4... 26913450
Trial 5... 26913450
  ✘  21:16:23|cl-0      OpenCL Error: clEnqueueNDRangeKernel -52
min/mean/max: 26913450/26913450/26913450 H/s
inner mean: 0 H/s

------------------------------------------------------------------------------------------------------

ethminer --version
ethminer version 0.12.0.dev2
Build: Linux/g++/Release

------------------------------------------------------------------------------------------------------

NVIDIA Driver Version: 387.34

------------------------------------------------------------------------------------------------------

Any way to fix this?

**Comment by smurfy** [comment]
Benchmark/Test is broken with opencl. this is a known issue.
Also for these who use a nvidia card use the cuda kernel by setting ``-U`` instead of ``-G``
