### ISSUE TITLE
setting wrong?

### ISSUE THREAD

**Issue by kenwong82** [ethereum-mining/ethminer#419]
![screen shot 2017-12-04 at 9 24 16 am](https://user-images.githubusercontent.com/34227906/33537391-3dd4adb4-d8f6-11e7-853c-ada708f99290.png)

/ethminer -G -S us1.ethermine.org:4444  -O 0xAa4007474e3a847aEE99b07E6aF625Aa6B868b8B --opencl-device 0

/ethminer -G --opencl-device 1 -S  asia1.nanopool.org:9999 -O 0xAa4007474e3a847aEE99b07E6aF625Aa6B868b8B

i have run this cmd and shown as picture, but i can't find any connection in the pool monitor and wallet, is it my setting wrong?

**Comment by smurfy** [comment]
i think nanopool only shows the worker if it submits valid shares, with 3MH/s this can take a while

**Comment by Simon0Harms** [comment]
append -RH -SP 1
Then the worker will report his hashrate to nanopool.

Perhaps, then he shows up

**Comment by kenwong82** [comment]
@smurfy how long will it take?

**Comment by smurfy** [comment]
> @smurfy how long will it take?

well depends a bit on your luck, you can also test @Simon0Harms suggestion.
I do not have such slow cards.

**Comment by smurfy** [comment]
@kenwong82 did our suggestions work?

**Comment by DeadManWalkingTO** [comment]
Test launch command:

`ethminer.exe -RH -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.test`

Try with latest Ethminer version and feedback please.
Thank you!

**Comment by JonasHodges** [comment]
is it safe to overclock the memory to +1000, i accidentally bought 6 GPU and made a rig to generate some profit. but later i figured its very low performance card. not like 1070Ti. so dont know what to do.

after reading some internet hint, i set TDP to 56 and Memory to +1000. i get the ETH 26.3Mh/s but as afraid that if it will fry the cards? i read somewhere the fans and cooling system only concerns the GPU chip. and all sensors are watching the GPU temp. the memory is not being monitor. so perhaps we will burn the GPU. because 1000 is maximum for this. please guide me what to do. and also if there any other algorithms best for GTX1080 windforce cards. would you please refer me there? i am bit disappointed after this huge investment the profit is not as expected.

thank you very much dear sir.
