### ISSUE TITLE
Doesnt work install ethminer 0.12.0

### ISSUE THREAD

**Issue by benoitmignault** [ethereum-mining/ethminer#428]
I have always a loop
[sans titre](https://user-images.githubusercontent.com/28330388/33744061-66a77b84-db7d-11e7-88e7-c61bd9f23685.png)

I have windiws 7 x64

**Comment by MariusVanDerWijden** [comment]
Have you checked your internet connection?

**Comment by smurfy** [comment]
@benoitmignault  are you sure you **REALLY WANT** to solo mine? If so you need to start geth and let it sync.

But based on the filepath, my guess is you just launched the executable without any additional commandline arguments and wondering what to do.

Ethminer does not have a GUI and you need to configure it using arguments.  If you need help consider joining us at gitter (https://gitter.im/ethereum-mining/ethminer)

**Comment by xhitm3n** [comment]
Im using Ethermine.org and using latest build 0.13.dev0 everything works fine W10 with R9 290 mining at 29 Mh/s thanks to all dev, il keep following the develompent since im planning on building a GPU Mining stack!

**Comment by Julix91** [comment]
For me running the `ethminer.exe` found [here](https://github.com/ethereum-mining/ethminer/releases) with admin priviledges didn't do anything, but I might be missing crucial info. My understanding was that the file would run an install - do I need other files in the same directory?
![image](https://user-images.githubusercontent.com/12877287/34335628-12aadf90-e905-11e7-8030-5557252d3097.png)

And yes internet is working.

**Comment by Julix91** [comment]
Nevermind, it's right on the [front page](https://ethermine.org/):
![image](https://user-images.githubusercontent.com/12877287/34336004-64075866-e908-11e7-93e7-84946dbff2ea.png)

A second file is necessary to install this - would be great (for newbs like me) if the exe came with a better error message, perhaps "no .bat file found in the same directory - create one with appropriate settings and try again".

@benoitmignault lemme know if this helped or if you're still having issues.

Cheers!

**Comment by android-dep** [comment]
@Julix91 try opening up an elevated command prompt and go into the directory where the miner is located in and instead of just executing the 1 exe file in the folder, execute it and add the " --help" switch after ethminer.exe like this `ethminer.exe --help`.

Most miners are coded to include some sort of a list of it's available functions and the syntax of the commands that it accepts to allow the user to perform the functions that it's capable of performing.

A readme file isn't always included with some of these open source applications but they usually do provide a basic list of available commands and switches if you just run them with the "--help" or "-h" switch or for windows applications it's usually "/?" to get list of available options.

**Comment by DeadManWalkingTO** [comment]
Test launch command:
`ethminer.exe -RH -X -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.test`
Try with latest Ethminer version and feedback please.
Thank you!
