### ISSUE TITLE
0.13rc4 CUDA on Ubuntu - strange behaviour with high grid size and block size

### ISSUE THREAD

**Issue by Dugy** [ethereum-mining/ethminer#561]
I tried playing with various parametres and found that the hash rate was significantly higher if I set block size to 512 and grid size to 32768. When I set the grid size to 65536, it was even higher. Changing other parametres made no significant difference.

Default parametres: 9.5 MH/s (typical value for GTX 980)
Block size 512, grid size 32768: 17.4 MH/s
Block size 512, grid size 65536: 33.4 MH/s
(I was mining in a pool, not benchmarking, benchmark yields results approximately twice as high)

However, the actual speed of finding shares did not appear to be higher, though it might have been just bad luck. A greater problem was that sooner or later it reported this error:

`CUDA0  FAILURE: GPU gave incorrect result`

After that error, no new shares were found.

I assumed that some short int is overflowing, but setting the value just below the maximum value of short int made no difference.

**Comment by AndreaLanfranchi** [comment]
Could you please retest with latest and report if the issue remains ?

**Comment by Dugy** [comment]
The error does not happen anymore, but it still reports a bogus hashrate. The number of solutions found is the same as with default parameters (it shows about 80% more).

Of course, there is a slight chance that this isn't true because there is some luck factor.

**Comment by farizluqman** [comment]
It is because, I believe, the GPU is still processing when switching occurs. I tried increasing block size and grid size, getting 35-60 Mhash/s on an M60, and it switches to new jobs with the average of 1000ms - 2000ms. Those were abysmal because you will lose shares (I'm not sure for solo mining). 

What I really hope in the future is: the support for high block and grid size, which involves in the betterment of the switching delays

I'm using this oneliner:
ethminer --farm-recheck 200 -G -S us2.ethermine.org:4444 -FS us1.ethermine.org:4444 -xxx.xxx -RH --cuda-parallel-hash 8 --cuda-block-size 256 --cuda-streams 4 --cuda-grid-size 131072

Getting 35-40Mhash/s
![https://i.imgur.com/58ddykY.png](https://i.imgur.com/58ddykY.png)

3402ms delay in switching to new jobs! yup, this explains why
![https://i.imgur.com/gQNfA52.png](https://i.imgur.com/gQNfA52.png)

Hopefully, there are ways to reduce delay with high block and grid size.

**Comment by DeadManWalkingTO** [comment]
I think this issue can be closed.
