### ISSUE TITLE
Hashrate help! GTX 1060 6 GB 

### ISSUE THREAD

**Issue by DiazLv** [ethereum-mining/ethminer#573]
Hi All,
I am quiet newbie in mining. just setup 2 GTX 1060 6 gb DDR5 (Hynix) but when first start hashrate around 15 ~ 17 mhs after overclock 19 ~ 21 mhs.
Never across beyond that hashrate. any of you able to help me what setting i have done wrong? 

Overclock setting:
- Power limit 65%
- Memory clock: +750
- Core clock: 0
- Fan: 70%

using ethermine 0.12.0

setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
ethminer.exe -U --farm-recheck 2000 --cl-local-work 256 --cl-global-work 16384 -S asia1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O <address>

I am also change set force P0 to off

**Comment by MariusVanDerWijden** [comment]
You use OpenCl to mine with Nvidia cards, On Nvidia GPU's its often better to use CUDA to mine

**Comment by satori-q3a** [comment]
For Micron and Hynix memories, that's what to expect.  My EVGA 1060 has a Micron and can't get past 21 MH without becoming unstable.

**Comment by DiazLv** [comment]
@MariusVanDerWijden in the setting "-U" mean mining with CUDA instead of OpenGL right?
i did using -G but the hashrate slightly lower 1 mhs

@satori-q3a yea so far for samsung not much people complaint about hashrate. it easily mine with 24mhs. Wonder anyone able to reach 24mhs with micron or hynix.

**Comment by ZeddBread** [comment]
Do you think it's due to the OS?

**Comment by jpoirier** [comment]
I'm running an ASUS GTX1060 6GB with micron memory on windows 10 that does a stable 23.4 mhs but any more tweakage for a higher hash rate causes problems.

- core voltage 0
- power limit 70%
- core clock -170
- mem clock +610
- fan speed 70%

Start-up is simple:

setx GPU_FORCE_64BIT_PTR 0
setx GPU_USE_SYNC_OBJECTS 1

ethminer.exe -U ...



Note, no need to set the following three environment variables since they're set in the etherminer/main.cpp file:

	// Set env vars controlling GPU driver behavior.
	setenv("GPU_MAX_HEAP_SIZE", "100");
	setenv("GPU_MAX_ALLOC_PERCENT", "100");
	setenv("GPU_SINGLE_ALLOC_PERCENT", "100");

**Comment by DiazLv** [comment]
@ZeddBread i am using windows 10. haven't try linux yet
@jpoirier any reason to under clock core? my one did not have any difference on hashrate

**Comment by jpoirier** [comment]
@DiazLv  to decrease energy usage

**Comment by DiazLv** [comment]
@jpoirier thx for the info

**Comment by DDDanny** [comment]
@DiazLv 
As I understood so far, the Samsung RAM can be pushed further, but at same speeds it is not faster...

+750 Mem stable @ 1060 is quite nice
You can compare the absolute Mhz below to see

my ASUS GTX1060 6OG gets instable there (Samsung RAM)

with (Win 10) - running since 6 months:
stock voltage
PL 60%
Clock -400 (Afterburner: 1455Mhz)
RAM +723 (Afterburner: 4622Mhz)
Fan typically 40%@43°C (~18°C room temp)
(Fansetting: 30%@35°C + 50%@50°C)
drawing 94Watts (HW Mon)
giving 23mh/s - compared to my 1070 (running PL 70%) it produces "only" 73% of the hashes - sure the power per mh is higher with ~3,75

**Comment by DiazLv** [comment]
Thx you for sharing @DDDanny 
I was tried ver 0.13rc7 its seem like stable. Around 20.7 ~ 21.3 mh/s instead of 19~21 

But when i check actual eth I receive same amount. Just information

**Comment by Ganga05** [comment]
running clymore on nanopool
my GPU is asus GTX1060 6GB
Power- 70%
Core clock - 110Mhz
Memory clock - 662Mhz

3 card 23-24 MH/s oc
3 card 19-20 MH/s oc
Can tell about 3 GPU problem

**Comment by pranash07** [comment]
I’m running 6 X ROG-STRIX-GTX1060-O6G-GAMING (Hynix)

Can’t seem to get more than that

Core voltage        0
Power limit          65%
Core clock          100
Memory clock    900
Fan speed          AUTO

21.2MH/s per card

**Comment by momowchang** [comment]
@pranash07 do you have any freezing with that oc settings? i have the same card with hynix mem.

**Comment by pranash07** [comment]
Nope no freezing.runs super stable on my current settings

**Comment by oscarn20** [comment]
hi, im new to this im mining with simplemining check my setting to OC, help me i thinks its ok im having no rejected share 
![oc set](https://user-images.githubusercontent.com/37267347/37253993-7cf5216c-250f-11e8-85b4-a2381d1f20a7.PNG)

im having this Mh/s
![hs](https://user-images.githubusercontent.com/37267347/37254002-9494ba08-250f-11e8-842f-6523a0e7ebc9.PNG)

this temp and fan %
![temp](https://user-images.githubusercontent.com/37267347/37254006-9da5ec84-250f-11e8-885c-a1618256757d.PNG)

gpu0 power color red devil rx580
gpu1 msi 1060 6gb hynix mem
gpu2 gigabyte 1060 3gb 
gpu3 gigabyte 1060 3gb
gpu4 gigabyte 1060 3gb

im a little scared because i think i overclock too much but its working good for 3 days now, and the electric bill its no i problem here

at first the gpu was giving me this

gpu0 power color red devil rx580  27mh/s (them i bios modded)  the oc setting doesnt affect this but if i put to 0 them the next card go back to 15mh/s
gpu1 msi 1060 6gb hynix mem 15mh/s out of box
gpu2 gigabyte 1060 3gb 17mh/s out of box
gpu3 gigabyte 1060 3gb 17mh/s out of box
gpu4 gigabyte 1060 3gb 17mh/s out of box

im giving this info to help anybody and to be help if im doing something wrong any advice will be much appreciated, thanks

ps: im waiting for some other cards

**Comment by pranash07** [comment]
Your temps seem High,do you think your cards will have the life longevity as you would hope for?

**Comment by invidtiv** [comment]
@oscarn20 
if you are using simpleminingOS then you cannot never put AMD and NVIDIA together , remove your GPU0 from that rig, things will work afterwards ;)

**Comment by invidtiv** [comment]
@oscarn20 
and put your fan to 100% you will fry quick your grafic cards with those temp.

**Comment by oscarn20** [comment]
@pranash07 @invidtiv thanks for the obsarvation i will remove the amd card and see what happens, and im going to pu the fan 100%

**Comment by oscarn20** [comment]
@pranash07 @invidtiv  i have a question> what is the recommended temp?

**Comment by pranash07** [comment]
Anywhere between 55-65 Degrees Celsius 
I wouldn't recommend going pass that especially if you want to get full life out of your cards.

**Comment by oscarn20** [comment]
@pranash07 thanks

**Comment by invidtiv** [comment]
yes I live in portugal and i try to keep them below 50C for nvidia and below 55C for AMD
anything above that and the cards stop working...

**Comment by oscarn20** [comment]
update:
oc settings
![oc 2](https://user-images.githubusercontent.com/37267347/37287496-4fd8270c-25db-11e8-9767-46b747675397.JPG)

gpu MH/s
![gpu2](https://user-images.githubusercontent.com/37267347/37287526-5e3e25e4-25db-11e8-9ba7-16b3e42a734d.JPG)

Temp and fan
![temp 2](https://user-images.githubusercontent.com/37267347/37287537-67803a84-25db-11e8-9fb6-e7c4088c5e60.JPG)

**Comment by venadHD** [comment]
Hynix memory forever will show less hashrate due timins.

My stable OC for **HYNIX** is 

- core voltage 0
- power limit 70%
- core clock -170
- mem clock +600
- fan speed auto

19.3 MH/s Gigabyte GTX 1060 3GB Version
From @jpoirier

**Comment by oscarn20** [comment]
@venadHD 
i tried those settings and get down to 17.3 from 19.7
i guess doenst work equal to diferrent brand because mine are a msi 1060 6gb hynix memory

**Comment by venadHD** [comment]
What is your current config for MSI Hynix memory?

**Comment by invidtiv** [comment]
ON good days Cclock -200 Mclock +1350 Power 60%

**Comment by oscarn20** [comment]
-100/+1300

**Comment by oscarn20** [comment]
but the hynix memory its i problem i will sell that card and buy another and hopefully not a hynix

**Comment by venadHD** [comment]
Cant go up as 1000

**Comment by ivanlucci1** [comment]
Is it normal Ethminer starting scripts for ~10min before start really mining works? Mine seems to be in slow motion on the first minutes LOL

**Comment by venadHD** [comment]
Can you post the script?
