### ISSUE TITLE
Windows Defender Security - Trojan:Win32/Fuery.A!cl - False Positive!

### ISSUE THREAD

**Issue by jbdman** [ethereum-mining/ethminer#605]
I am assuming this is a false positive, but only occurs on 0.13.0rc9, I was able to download and use 0.13.0rc8 without issue.

**Comment by AndreaLanfranchi** [comment]
Not an issue indeed.
Many AV programs detect miners as malware due to various reasons:

1. Several closed source miners use packers that are in common with other kind of malware
2. The "warning" is issued to protect users which may have a miner on board without their knowledge

This miner is completely open-source and you can compile the source yourself if you do not trust the binaries.

Anyway analyze [Virus Total for ethminer 0.13.rc9](https://www.virustotal.com/#/file/96bcf26d33cd90634835def5317558c59ad5c27a89bdcc4eb105e9f590ec5e61/detection) and you will see it gets detected as "malware miner" ! Really ? What a surprise.

**Comment by satori-q3a** [comment]
I've had the bogus warnings on previous 0.13 release candidates, I just ignored them. Altho I am tempted to allow it to be sent as a part of the av auto send back to MS just for giggles.

**Comment by jean-m-cyr** [comment]
@satori-q3a In a previous life, I did shareware for Windows. These false positives from security packages that give users little other than a false sense of security have been a problem for a long long time. Don't see it being resolved anytime soon!

**Comment by DeadManWalkingTO** [comment]
I really hate false alarms.
That's why i use open source software. (Always know what the program exactly do.)
No wearies about AV warnings.
