### ISSUE TITLE
HR decrease of 1% since 0.13.0

### ISSUE THREAD

**Issue by sfornengo** [ethereum-mining/ethminer#630]
The last few commits since 0.13.0 lower my reported HR by about 1% (stable 357-358MH/s to stable 353-354MH/s.
I don't know why, but it does ! I can only see change #618 as culprit.
Reverting to 0.13.0 restore my reported HR

**Comment by sfornengo** [comment]
I think the problem comes from the starting nonce:

+	uint64_t get_start_nonce()
+	{
+		// Each GPU is given a non-overlapping 2^40 range to search
+		return farm.get_nonce_scrambler() + ((uint64_t) index << 40);
+	}
+

A gpu at 30MH/s can sweep the 28 last bits of the nonce in less than 10s.
So each time farm.get_nonce_scrambler() return by chance a pattern of 64 bits as 24[x]12[1]28[x] we ensure that gpu will overlapping during the search !

Am I wrong ?
That could explain why I see a 1% drop...

**Comment by sfornengo** [comment]
Reasoning error... sorry for the noise.

**Comment by chfast** [comment]
cc @jean-m-cyr

**Comment by jean-m-cyr** [comment]
What's gone in since 13.0?
- some console formatting stuff.
- equally spaced search ranges with once per run randomize.

Got a question? Are all nonces equally probable to solve the problem. What I mean is, has this been mathematically shown in some white paper, or is it just legend? Intuitively it seems to be the case, but...

**Comment by sfornengo** [comment]
I agree, I can not understand why my reported HR is impacted by this commits.
Could someone else confirm ?

**Comment by efrasyad** [comment]
Personally, I don't rely on reported hashrate, I always pay close attention to my average hashrate, because.
I tried the other famous mining software for couple of days a month back and tried it again couple (to see if there is any improvement, even there is no software updates for months) of days ago, it indeed reported higher hashrate, but the average hashrate reduced 3-5%, not to mention the occasional random crash (mostly caused by devfee mining) and higher stale share rate.

**Comment by jean-m-cyr** [comment]
I wish I had the time and resources to do controlled A/B experiments, but I don't! I have to rely on averaging out what you guys report. :-)

Thank you BTW.

**Comment by sfornengo** [comment]
I retested for 8 hours today and do not see HR decrease this time.
It remains an enigma concerning my two previous tests, the observations were clear and stable about decreasing HR by more than 1%...
So closing issue, sorry for the noise ;)
