### ISSUE TITLE
Pool Reports Worker Not Seen But Output From Worker Indicates Mining Still in Progress

### ISSUE THREAD

**Issue by clayv** [ethereum-mining/ethminer#632]
I have seen this occur twice now with the 0.13 build with a single GPU and an avg. hash rate ~23.8 MH/s.  First time occurred approximated 8 hours after worker/program start and the second time was closer to 36 hours. I'm using ethermine.org for the pool.
I will get an email message from ethermine.org stating that the worker has been seen for a while and effective hash rate for the miner decreases.  Looking at the output in the terminal window (running on Windows 10), shows that mining activity continues on  the GPU and it continues to receive new jobs from pool.
In both occurrences the worker did not reappear in ethermine.org for more than 10 hours.
Stopping and restarting the worker fixes the problem without rebooting the machine.

**Comment by DekInc** [comment]
I have also this problem, i think maybe it is in the pool, sometimes the effective hashrate is down really fast and i use claymore and does not go up, so maybe it is something messy with pool server, i think maybe an option to show ping to server had to be add... or something similar

**Comment by AndreaLanfranchi** [comment]
I had this same problem this night. Unfortunately my watchdog was not active.
Here is the situation : 

1. at a given time ethminer reported this (usual) error

`CUDA error in func 'search' at line 491 : an illegal memory access was encountered.`

2. At the very same moment I record this logs in dmesg:

```
[78093.395644] NVRM: GPU at PCI:0000:04:00: GPU-1c18bd34-a3e0-690f-545f-f3c66375de14
[78093.395647] NVRM: GPU Board Serial Number:
[78093.395649] NVRM: Xid (PCI:0000:04:00): 31, Ch 0000001a, engmask 00000101, intr 1000000
```
3. From that moment ethminer (which did not stop or crash) continued (apparently) "mining" for over 12 hours but did not report any found share. New jobs continued arrive from the pool (thus connection was kept) and ethminer continued reporting his hashrate (strace confirmed the tcp conversation was still on).

It's strange that an error like this causes the program to stop mining but the program itself continues running.

This problem is related to #596

**Comment by MasonLyons** [comment]
Can confirm that I'm also getting this happen to me.

**Comment by Xeowolf** [comment]
I was getting CUDA error in func issues and ethminer would stop mining but continued to run. I fixed this by replacing a bad riser. Tracking down the bad riser can be tedious but that is what was causing it. I have been running for 60 hours now without issue.

**Comment by sportsbook123** [comment]
Would be nice if the log could specify the offending card along with the CUDA error lines...so that people will know which cards to check... eg, I have 13 nvidia cards on each rig and usually it goes without error for days, so I can't just keep changing risers hoping to nail the one that's (possibly) broken.

**Comment by DeadManWalkingTO** [comment]
Check and replase bad rizers.
Change rizers in to same version.
Try latest version of miner and feedback please.
Thank you!

**Comment by sportsbook123** [comment]
Already using the latest version of software and risers. The issue appears to be somehow related to overclocking in combination to GPU temperature (for instance same card with same OC as others will trigger the error when it gets hotter than 55 degrees, while others with the exact same OC settings will work fine as long as they stay around 40-45 degrees; but then, if dropping the mem clock the cards will work regardless of temperature), when a card's memory is pushed to the limit it will misbehave and the GPU triggers that exception. 

I am not sure if the nvidia driver reports which card has failed or not, but if it does then it would be really good if ethminer would log this so we won't have to guess which card is at fault, it's a tedious process when you have lots of cards on the same rig. On a 6 GPU rig it can take up to 2 hours of trial and error.

**Comment by AndreaLanfranchi** [comment]
This was likely related to boost's io service not being persistent.
Closing for now.
Feel free to reopen if it happens again.
