### ISSUE TITLE
Console colors on windows QUESTION

### ISSUE THREAD

**Issue by evlo** [ethereum-mining/ethminer#684]
Is it possible to have color console on windows like it is in linux?

**Comment by XhmikosR** [comment]
https://github.com/ethereum-mining/ethminer/pull/226

**Comment by DLS-bau** [comment]
![ethminer](https://user-images.githubusercontent.com/27926557/35780122-cced6f12-09df-11e8-9311-b4dd8b8d6282.PNG)
Yes, it's possible and quite easy to achieve. I do it like this since forever. 
See the attached diff against the last 0.14.dev1 if you want to do it yourself. It will probably break building on Linux but I don't care :)

[win_color_diff.txt](https://github.com/ethereum-mining/ethminer/files/1693169/win_color_diff.txt)
