### ISSUE TITLE
After running the BAT it configures and is missing DLL files

### ISSUE THREAD

**Issue by Dudleydogg** [ethereum-mining/ethminer#722]
yes I installed the C++ libraries still same issues.
since you guys know about that error why do I have to study threads for hours isn't there just a one click easy solution?
The web site clearly stated this was easy to get  up and running.
but NOPE

**Comment by MariusVanDerWijden** [comment]
> since you guys know about that error

We don't know about that error... can you post a log of it?
Which DLL's are needed? Do you have a nvidia or an amd GPU?
Did you install the cuda runtime/toolkit?

**Comment by MariusVanDerWijden** [comment]
Please keep in mind, that we do all of this for free, theres no fee involved and we work on it in our spare time

**Comment by DeadManWalkingTO** [comment]
I also had a problem like this in the past, but I finally found that the problem was to install the libraries installed in a different language / version.
My suggestion is to uninstall libraries and install them again after making sure they are the right ones for your system. 
Simply copy and paste into the program or system folder will make things worse.
If you give more details about your problem you will be able to get more detailed instructions.

**Comment by Dudleydogg** [comment]
Was Strange because I had all them installed vc_redist.x64 and vc_redist.x86, I removed both, rebooted the PC, then installed both the 64 and the 86 again.  Then I was able to start the miner with out the dll error.  Thanks guys for responding to me Yes it was Nvidia GPU
