### ISSUE TITLE
Stale shares last 24h (only me)

### ISSUE THREAD

**Issue by DeadManWalkingTO** [ethereum-mining/ethminer#775]
Hi@all
In the last 24h i have double stale shares @ ethermine.org.
Anyone have the same problem or just me?

(Win10 - NVidia - Master Compile)

**Comment by Davesmacer** [comment]
I'm using latest master and didn't have the problem. It happened to me a couple of days ago. Stale shares doubled suddenly. I restarted my miners and routers and everything got to regular work, but I couldn't see what the issue was. I thought it was my network being overloaded or something related...

**Comment by DeadManWalkingTO** [comment]
I reboot system.
I restarted my router. 
I rebuild master again.
Nothing!
BTW stale shares normalize in the time. I believe was a network overload.
