### ISSUE TITLE
CTRL-C weird behaviour

### ISSUE THREAD

**Issue by Davesmacer** [ethereum-mining/ethminer#798]
Hello people!

I just wanted to write here an issue I encountered to see if I'm the only one experiencing it. I'm not sure if it's something about my cards, drivers or OC settings. 

I was testing some builds of the program so I had to CTRL-C a terminal when it was working OK. After I did that, I saw that some of my Nvidia Cards came back up with half (sometimes 60-70%) of their hashrate. I had to close the terminal (sometimes more than once) to get the rig fully working. 

I was wondering if it's possible for the process to keep using some card resources even when it has been killed with CTRL-C?

This is not an important issue, as I always can get it back up without rebooting, but is still and issue.

Thank you for your help.

**Comment by SnowLeopard71** [comment]
Yes, I've also had bizarre behaviour when stopping a running miner with CTRL-C, but not every time.  
Earlier, I stopped a nvidia one and had no problems.  I restarted it in opencl mode because I wanted see hashrate difference on nvidias in cuda vs opencl (out of curiosity).
The CTRL-C for the opencl gave errors, dumped core, and bizarrely re-ran the wrapper script I use -- which restarted the miner in cuda mode again since I'd edited the script again.
On a different rig which also runs AMDs, stopping the nvidia miner has given NRM Xid 61 error.

I can't be 100% certain, but I don't think this was happening with 0.13.0 or earlier.

**Comment by Davesmacer** [comment]
Yes, it is not happening every time! Just once in a while... Do you think this could be due to HW monitors?

**Comment by SnowLeopard71** [comment]
It shouldn't be the "fault" of HW monitors, but could still be related in the sense that the problem might only be occurring if CTRL-C is hit at moment HWMON code is active...   
It's basically a race condition.

**Comment by Davesmacer** [comment]
Yeah, or something related... @smurfy are you guys using any debugging tool? Maybe with some gdb breakpoints I could be able to get into the problem

**Comment by smurfy** [comment]
I don't use a debugger. 

Also I am currently trying to fix some stuff related to miner shutdown. I hope this will fix this issue too. I already identified some problems, which I fix one by one. 

But as it always is, one problem leads to another ;) so lot's of small fixes

**Comment by Davesmacer** [comment]
Awesome @smurfy! Let me know if I can help you out somehow...

**Comment by chfast** [comment]
Can you test https://github.com/ethereum-mining/ethminer/releases/tag/v0.15.0rc1 ?
