### ISSUE TITLE
fatal cuda unknown error ... func dev::eth::cudaminer::search at line 504

### ISSUE THREAD

**Issue by satori-q3a** [ethereum-mining/ethminer#880]
ethminer 1.4.0 dev-3
windows 10 Fall Creators 2018 edition / March 2018 update
nvidia 391.05
7 gpu nvidia rig // (4) 1070, (2) 1050ti, (1) 1060
(3) mounted on 16 pci-e slots
(4) connected to external egpu box via 1x to 4 pci-e mux card
ethminer running on rig since 1.2.0, no real problems

ethminer 1.4.0 dev-3 running for over a week, miner failed once before but was unable to determine the error.  the current batch file now has a PAUSE after the exe statement, to capture the screen when it fails.

Error on screen says:
Fatal GPU Error : CUDA error in func dev::eth::cudaminer::search at line 504 unknown error

---------

Update:

Upon further inspection, I suspect the oldest card may be susceptible to hard memory errors when overclocked.  It's  a year older than the rest and I tend to keep that card less overclocked than the others, I'll tweak it down a bit more.

**Comment by momowchang** [comment]
I have the same issue just today. I was mining nonstop for a week then this happened. First the hashrate will abnornaly increase from my normal speed for about +40mhs and it will continue going up and down until this error pops up. Restarted the system and ethminer, waited for about an hour and same thing happened. I dont think I overclocked them since they were working fine for about a month now without crashes with the same oc settings.

**Comment by satori-q3a** [comment]
For my windows system, the gpu hard memory errors results in the nvidia desktop driver itself being reset which then causes the cuda error in ethminer.  The side effect is that the failing gpu has it's clockings set to default while the other gpus remain unchanged.

**Comment by AndreaLanfranchi** [comment]
Outdated.
Closing
