### ISSUE TITLE
GPU0 and GPU1 HWINFO data swopped

### ISSUE THREAD

**Issue by StevenV009** [ethereum-mining/ethminer#884]
Hi. I am running 0.14.0-dev3 on a clean ubuntu installtion. Using the -HWINFO flags, I have noticed the temp, hashrate, pwr and fan speed info is swopped between GPU0 and GPU1. When connecting via the api using AwesomeMiner to monitor as an example, it is also swopped here. I have tested on 2 x MB with the same results. I have a1050Ti as GPU0, and a P106-100 as GPU1.
![image](https://user-images.githubusercontent.com/27699919/37309949-2c0ee426-264b-11e8-8012-58a9aca09c37.png)
 
![image](https://user-images.githubusercontent.com/27699919/37310166-c73e1b06-264b-11e8-9664-d776a7168c1c.png)

 Otherwise, really awesome. thanks

**Comment by smurfy** [comment]
well, what do you mean by swapped?  
Since dev3  there is a pci-id based matching so while maybe the order of the cards is different, the hwmon data should be on the "right" card.

compare fan values of nvidia-smi (without params) and ethminer. And the values should match up.

Ethminer uses cuda device order which can differ from the order nvidia-smi reports. (thats why we added pci-id based mapping).

You also can control cuda device order via:

``export CUDA_DEVICE_ORDER=PCI_BUS_ID``

Hope this helps.  If the mapping is indeed wrong please tell us so we can investigate, but i'm quite sure it is correct.

**Comment by StevenV009** [comment]
@smurfy , thank you for your reply, and clearing up.

I ran the following command: ethminer --list-devices

![image](https://user-images.githubusercontent.com/27699919/37330790-de7f50f0-26aa-11e8-951d-ed5136623bdb.png)

I am not experienced enough to mess around with the cuda device order's, but now understand there are different orders. As a user, it was just confusing having ethminer display GPU0 with stats from my P106, which is actually GPU1 on nvidia-smi...

The learning curve is going vertical. :)
