### ISSUE TITLE
ethminer 0.14.0.dev4 - 15% stale shares

### ISSUE THREAD

**Issue by GrannyCryptomaster** [ethereum-mining/ethminer#895]
I ran today the new version and in half an hour I got 15% stale shares on ethermine.
With dev3 all was working fine, 1-2% stales. I will test it again in a few days, maybe was something wrong with my network...

RIG: Win 10 x64, 6x GTX 1060 3GB Hynix mem, core -100, mem +500, power 65, temp 83.

**Comment by l4Dream** [comment]
same problems with .dev4 , lot of stales on ethermine.org (win10, 4x1050ti)
parameters:
ethminer.exe -U -S eu1.ethermine.org:5555 -SF us1.ethermine.org:5555 -O <Your_Ethereum_Address>.<RigName> -RH --stratum-ssl
btw, miner does not report hashrate to pool as well, so I returned to .dev3

**Comment by GrannyCryptomaster** [comment]
I use the same batch file... I noticed the missing hashrate report too; so the stales were from miner, not from my network. 
I returned to Claymore's :)))

**Comment by l4Dream** [comment]
on the reddit there was a post https://www.reddit.com/r/EtherMining/comments/6h01sc/is_it_worth_switching_from_genoil_ethminer_to/diuf89o/  - i read that info around this thread, where an investigation was conducted about the devfee, extensive tests were conducted (1 month), a lot of screenshots with evidence were laid out. it turned out that on the addresses of the devfee and hashrates that the claymore is collecting, not everything is as smooth as he writes, in particular, abusing burst mining during the farm for the claymore dev, and hashrates was much higher than they should be (not as bad as it seems for typical miner but destructive for network and pools). In any case, I myself tested this miner and found no difference between the hashrates. plus I love opensource, so I continue to use the ethminer.

**Comment by GrannyCryptomaster** [comment]
Yep, hashrates are the same. I tested both for 24h, with 6h pause between. I don't look at hashrates and accepted shares, I just look at the profits. It's the only thing that matters. 
So, ethminer gave me 2,5% more ETH than Claymore's. 
I must mention that I used Claymore's 11.3 that had some problems with stale shares (I saw that on ethermine), but now in version 11.5 it seems they resolved it. I used ethminer dev3. It was very stable and reported corectly the hashrates. Now I started Claymore 11.5 and I will update this post after the 24h test.
If both miners have the same efficiency, the difference must be only 1% - Claymore's dev fee.
I like no dev fee and open source too, but stability is more important.

**Comment by aenciso** [comment]
Don't know. I'm pretty sure claymore is just a layer built on top of ethminer with some modifications for dev fees and dual mining. I have used both and fond ethminer a little but unstable on overclocked cards. I'm going to start testing ethminer's dev versions to check if they've been improved. Will post my findings.

**Comment by AndreaLanfranchi** [comment]
My two cents.
Ethminer 0.14.0.dev1 with 6x Gtx 1060 Dual on Ubuntu 16.04

Clock -180
Mem +1970
Power 80w

Not a glitch for over 8 days. Stale share rate roughly 2%

![2018-03-16](https://user-images.githubusercontent.com/15280851/37540738-67504ae2-2958-11e8-9fe5-dd94b37cf553.jpg)

Ethminer rocks.

**Comment by satori-q3a** [comment]
I've taken 0.14.4 more seriously and it seems that nanopool is reporting a 5% increase in hashrates while stales are at 1.5% (0.14.3 stales were at 0.5%).  But the gaming rig with less memory overclocking shows a stale rate of 0.5%, in addition to a 5% increase in hashrates.

I had tried it before but regressed back to 0.14.3 because the hashrates seemed off, turns out 0.14.4 does not like block-size of 256 for nvidia cards but does play nice with block-size 128.

**Comment by xtraa** [comment]
FYI: Firefox 60.0.1 for Windows is now hoaxing in a good attempt about malware when you dl the .14 release. Just for the people that prefer mozilla over chrome.
