### ISSUE TITLE
ethminer 0.14 rc0 ms defender detecs virus

### ISSUE THREAD

**Issue by TeMeise** [ethereum-mining/ethminer#933]
Hello,

i ve downloaded the latest version as mentioned in the title, the Microsoft Defender decets it as a severe Thread. 

additionally i ve uploaded it to virustotal.com. Some scanners say they found something, the most didnt find a thread.

Is it safe to use or not? 

Here is a screenshot of the windows defender alert

![screenshot-virus](https://user-images.githubusercontent.com/4975653/37878573-7bd4a0de-306b-11e8-95ba-206763fc90b0.png)

Best,

Te

**Comment by smurfy** [comment]
Most anti-virus programs detect miners as threat, these days. The precompiled exes **do not** contain anything nefarious, you even can compile them from source and your anti-virus might detect them as virus.

So its not really a false positive, because some trojans now include miners to mine for their authors.
But if YOU use ethminer it will mine for YOU
