### ISSUE TITLE
Latest ethminer release marked as Trojan:Win32/Fuerboos.C!cl by Windows defender

### ISSUE THREAD

**Issue by Olegatorius** [ethereum-mining/ethminer#934]
ethminer-0.14.0rc1-Windows.zip . 
Im sure it`s a false positive.

**Comment by DeadManWalkingTO** [comment]
False positive.
It's Open Source project!!!

**Comment by smurfy** [comment]
Most anti-virus programs detect miners as threat, these days. The precompiled exes do not contain anything nefarious, you even can compile them from source and your anti-virus might detect them as virus.

So its not really a false positive, because some trojans now include miners to mine for their authors.
But if YOU use ethminer it will mine for YOU
