### ISSUE TITLE
Does Ethminer have problem with 1060 3GB?

### ISSUE THREAD

**Issue by fynxer** [ethereum-mining/ethminer#954]
Please let me know if Ethminer works with 3GB cards!

i have 8pcs of nVidia 1060 3GB

Ethminer rc2 stop working during start up, have some problem allocating

The last this it lists is:
**Allocating light with size: 40107968**
And the stops working

The page file is 48GB

See picture
![capture](https://user-images.githubusercontent.com/15197974/38095178-1339ad0a-3370-11e8-99e9-6688d832d6c6.PNG)

**Comment by dmkrovichmix** [comment]
Having a similar issue with 3GB GTX nvidia cards.  6GB GTX nvidia card works fine.

**Comment by Saurelius** [comment]
I had same problem today on windows 10 with my 1060 3GB cards. Rollback NVIDIA driver to version 388.13 (27 oct 2017) helped to solve problem.

**Comment by satori-q3a** [comment]
Are you running windows desktop on one of the nvidia cards, if so, windows 10 fall creators edition loads overhead into the graphics cards, causing the DAG load to exceed 3 gig.

If your system supports it, use the motherboard's integrated video for the desktop, and do not connect any video cables on the nvidia cards.

**Comment by Saurelius** [comment]
satori-q3a.  Windows desktop running on integreted core of Intel processor.

**Comment by Spudz76** [comment]
3GB is very very very very tight with the currently ~2.6+GB DAG

I am still running on a 3GB AMD HD7970 (Tahiti Pro) which shows 478711808 (456.5MiB) free but I'm not sure that's completely accurate it may be more like 223480422 (213.1MiB) as that is what is shown for max allocate right now in clinfo (with ethminer running)

Make sure you have all the GPU_* environment vars set properly, especially GPU_FORCE_64BIT_PTR=1 although I'm not sure that does much in Windows on CUDA (you ARE using CUDA not OpenCL, right?)  I'm pretty sure it mattered with the same stuff but Linux (6GB though / still crashes DAG generate without the 64 bit force even if you weren't out of VRAM / plenty of swap / etc)

I am running 6x GTX 1060 on Win7 with 12GB swap (mainly because 32GB SSD) so to most extents ridiculous amounts of swap is entirely BS.  Complete BS in Linux, I'm running 4GB swap in most of mine.  Certainly not whatever "rule" that seems ubiquitous about swap == total of VRAMs.  I mention because I doubt that has anything to do with it in this case also / actually I think 48 is faaaar too much.  I wouldn't go much over 16.

Also try it out with one card installed instead of a million, reduce confusion and fuzz vectors.

**Comment by Saurelius** [comment]
Spudz76 if you are runiing yours 1060 3 GB on Win 7 - you should not have a some problems, because the windows 7 not need lot of gpu memory

**Comment by dmkrovichmix** [comment]
In my case everything was working fine and just stopped yesterday.  I hadn't changed any configurations.

**Comment by Tazoid** [comment]
I two exactly the same PC configs. One worked one didn't. Thx to this thread i figured why. It really was only because of drivers. One computer updated and the other didn't. Rolling back driver to 388.31 fixed it.

**Comment by n0v3xx** [comment]
I have since yesterday the same issue with "Allocating light with size: 40107968". I have 6x 3GB 1060 with Ethminer v13. But the v14 the same error. (Windows 10 Pro)

Any solutions?

**Comment by lee-gravity** [comment]
I've been having the same problem with running a gtx 1060 3Gb on the mac. It was working until about 1 week ago then it just failed. All I get is an error saying segmentation fault 11 then it fails. I also have a gtx 1050 Ti 4Gb and that works fine (albeit with a much lower hash rate). Assume this is down to the lack of memory on the 1060. Luckily I just bought it so I'm going to send it back

**Comment by AndreaLanfranchi** [comment]
3GB is (almost) no longer enough to mine ethereum as the DAG size + the ram needed by the mining threads + (eventually) the ram occupied by the Windows os is plus 3gb.
You may elongate the mining life of those GPUs using linux instead of windows but ... it won't last long.

**Comment by n0v3xx** [comment]
@AndreaLanfranchi , why? Windows can use the integrated Intel GPU. The nvidia card should be clean 3 GB RAM for mining :/

**Comment by lee-gravity** [comment]
Given the above with the 3Gb cards I assume 4Gb cards won't have much time left before they dont have enough memory

**Comment by AndreaLanfranchi** [comment]
@n0v3xx ... unfortunately not. Windows always uses a tiny amount of memory from every recognized GPU.
Also BIOS settings would apply.

**Comment by AndreaLanfranchi** [comment]
@lee-gravity ... you're right but there are still a couple of years of time.
Use this site to check the DAG file size (only) and manually add roughly 0.5 Gb extra for kernel processes

https://investoon.com/tools/dag_size

**Comment by n0v3xx** [comment]
Ok thats suck, i install windows 7 now for testing. I give feedback then

**Comment by jean-m-cyr** [comment]
Use Linux if you want to mine on 3GB

**Comment by AndreaLanfranchi** [comment]
Please close issue as this is not related to ethminer. It's a problem of DAG size.
