### ISSUE TITLE
AV detects it

### ISSUE THREAD

**Issue by PeshBG** [ethereum-mining/ethminer#972]
I wonder if i compile it myself will the AV detect it? (i don't want to white list it) Has anyone tried?

**Comment by smurfy** [comment]
yes, at least mine detects own compiled ones

**Comment by smurfy** [comment]
@TimMcCarty 
Most anti-virus programs detect miners as threat, these days. The precompiled exes do not contain anything nefarious, you even can compile them from source and your anti-virus might detect them as virus.

So its not really a false positive, because some trojans now include miners to mine for their authors.
But if YOU use ethminer it will mine for YOU

**Comment by TimMcCarty** [comment]
I figured that it was a false positive, and I am not surprised that windows detects the code as such due to the amount of malicious mining code there is 'out there' just looking for some confirmation - that others are:
a. seeing it reported that way also (so that i can be assured (to some degree) that it's not something else already on my system)
2. to prompt others to report it if they have seen suspicious activity from running it

**Comment by PeshBG** [comment]
the game of cat and mouse works like this - new version of the malware is build, av detects it add signature.. and the cycle starts again. :) In my case i am using it on a PC where AV must run without white listing. The latest dev debug version is at this point not detected. I wonder if some changes to the code will produce a new unique hash that AV wont detect due to the lack of such signature in the wild.

**Comment by satori-q3a** [comment]
Yep, I'm forced to download it to a folder that's excluded from the AV scan, as well as setting the AV to exclude the ethminer dirs.
