### ISSUE TITLE
 ethminer-0.14.0rc4-Windows.zip gets flagged by Windows Defender for a trojan upon unzip

### ISSUE THREAD

**Issue by S204STi** [ethereum-mining/ethminer#999]
Contains something called Win32/CoinMiner.C!cl

**Comment by alptolga** [comment]
So?

**Comment by Hakkk2002** [comment]
Not a false... Defender tells you it is a coin miner which is true :)

**Comment by Xeroeth** [comment]
Most antivirus soft atm detects any mining software as malicious. Partially they are right, there is a ton of trojan/viruses that infect your PC and mine in the background camuflaged as something else, mainly for monero alghoritms, since it can use a CPU for that. In this case it's a false alarm :) Can't do anything about it, just add an ignore rule.
